// test_sourcemap.cpp — T2.6 mbun.sourcemap test suite.
//
// Known-answer vectors are generated by bun's reference VLQ/mappings codec (the
// oracle), preserving assertion semantics (see AGENTS.md TDD rules). Sources:
//   - .mbun/bun-ref/src/sourcemap/VLQ.zig            (encode/decode reference)
//   - .mbun/bun-ref/src/sourcemap/Mapping.zig        (parse / find)
//   - .mbun/bun-ref/src/sourcemap/lib.rs             (append_mapping_to_buffer,
//                                                     SourceMapPieces::finalize)
//   - .mbun/bun-ref/test/js/bun/sourcemap/internal-sourcemap-roundtrip.test.ts
//       (the reference `encodeVLQ` / `decodeMappings` / `referenceFind` codec,
//        used verbatim as the oracle to compute the vectors below)
//
// DEFERRED(S1) — require the bun runtime / real files,登记 for the bun:test
// runner (T3.4) and module loader (T3.3), out of scope for pure-logic S0:
//   - internal-sourcemap.test.ts: Bun.spawn transpile + stack-trace remapping
//     (InternalSourceMap varint blob, UTF-16 column semantics)
//   - internal-sourcemap-roundtrip.test.ts: `bun:internal-for-testing`
//     internalSourceMap round-trip against a transpiled module
//   - test/js/node/test/fixtures/test426/source-map-spec-tests.json: loads
//     external .js.map fixture files (JSON source-map validation conformance)
//   - test/bundler/*sourcemap*: itBundled end-to-end bundler sourcemap output
import std;
import mbun.sourcemap;

namespace {

using mbun::sourcemap::append_mapping;
using mbun::sourcemap::finalize_pieces;
using mbun::sourcemap::find_mapping;
using mbun::sourcemap::Mapping;
using mbun::sourcemap::MappingsBuilder;
using mbun::sourcemap::parse_mappings;
using mbun::sourcemap::SourceMap;
using mbun::sourcemap::SourceMapShift;
using mbun::sourcemap::SourceMapState;
using mbun::sourcemap::vlq_decode;
using mbun::sourcemap::vlq_encode;

int gChecks{0};
int gFailures{0};
constexpr int MAX_FAILURE_PRINTS{25};

void report_failure(std::string_view what) {
    ++gFailures;
    if (gFailures <= MAX_FAILURE_PRINTS) {
        std::println("  FAIL {}", what);
    }
}

void check_eq_str(std::string_view actual, std::string_view expected, std::string_view src) {
    ++gChecks;
    if (actual != expected) {
        report_failure(std::format("[{}] got \"{}\", expected \"{}\"", src, actual, expected));
    }
}

void check_eq_int(std::int64_t actual, std::int64_t expected, std::string_view src) {
    ++gChecks;
    if (actual != expected) {
        report_failure(std::format("[{}] got {}, expected {}", src, actual, expected));
    }
}

void check_true(bool cond, std::string_view src) {
    ++gChecks;
    if (!cond) {
        report_failure(std::format("[{}] expected true", src));
    }
}

// ── VLQ encode/decode ──────────────────────────────────────────────────────

struct VlqCase {
    std::int32_t value;
    const char* encoded;
};

// oracle: bun reference codec (internal-sourcemap-roundtrip.test.ts encodeVLQ)
constexpr VlqCase VLQ_CASES[]{
    {0, "A"},          {1, "C"},          {-1, "D"},         {2, "E"},
    {-2, "F"},         {15, "e"},         {16, "gB"},        {-16, "hB"},
    {17, "iB"},        {32, "gC"},        {-32, "hC"},       {100, "oG"},
    {123, "2H"},       {-123, "3H"},      {255, "+P"},       {256, "gQ"},
    {-256, "hQ"},      {1000, "w+B"},     {-1000, "x+B"},    {1023, "+/B"},
    {1024, "ggC"},     {65535, "+//D"},   {65536, "gggE"},   {-65536, "hggE"},
    {1000000, "gkh9B"},{-1000000, "hkh9B"},
    {2147483647, "+/////D"}, {-2147483647, "//////D"},
};

void test_vlq_encode() {
    for (const auto& c : VLQ_CASES) {
        check_eq_str(vlq_encode(c.value).view(), c.encoded,
                     std::format("vlq_encode({})", c.value));
    }
}

void test_vlq_decode() {
    for (const auto& c : VLQ_CASES) {
        auto d{vlq_decode(c.encoded, 0)};
        check_true(d.ok, std::format("vlq_decode(\"{}\").ok", c.encoded));
        check_eq_int(d.value, c.value, std::format("vlq_decode(\"{}\").value", c.encoded));
        check_eq_int(static_cast<std::int64_t>(d.next), std::strlen(c.encoded),
                     std::format("vlq_decode(\"{}\").next", c.encoded));
    }
}

void test_vlq_roundtrip() {
    // Encode then decode must reproduce the input across a wide value range.
    for (std::int32_t v{-100000}; v <= 100000; v += 37) {
        auto e{vlq_encode(v)};
        auto d{vlq_decode(e.view(), 0)};
        if (!d.ok || d.value != v || d.next != e.len) {
            report_failure(std::format("vlq roundtrip {} -> \"{}\" -> {}", v, e.view(), d.value));
        }
        ++gChecks;
    }
    // large magnitudes near i32 bounds
    for (std::int32_t v : {2000000000, -2000000000, 1073741823, -1073741823}) {
        auto e{vlq_encode(v)};
        auto d{vlq_decode(e.view(), 0)};
        check_true(d.ok && d.value == v && d.next == e.len,
                   std::format("vlq roundtrip large {}", v));
    }
}

void test_vlq_decode_multi() {
    // Consecutive decodes advance `next` correctly over a 4-field segment.
    // "KAAI" = [5, 0, 0, 4] (oracle-derived from example mappings).
    std::string_view seg{"KAAI"};
    auto a{vlq_decode(seg, 0)};
    check_eq_int(a.value, 5, "decode_multi[0]");
    auto b{vlq_decode(seg, a.next)};
    check_eq_int(b.value, 0, "decode_multi[1]");
    auto c{vlq_decode(seg, b.next)};
    check_eq_int(c.value, 0, "decode_multi[2]");
    auto d{vlq_decode(seg, c.next)};
    check_eq_int(d.value, 4, "decode_multi[3]");
    check_eq_int(static_cast<std::int64_t>(d.next), 4, "decode_multi end");
}

void test_vlq_decode_invalid() {
    // A non-base64 byte at `start` yields ok=false with no advance.
    auto d{vlq_decode(" ", 0)};
    check_true(!d.ok && d.next == 0, "decode invalid char");
    auto e{vlq_decode("", 0)};
    check_true(!e.ok && e.next == 0, "decode empty");
}

// ── mappings generation ────────────────────────────────────────────────────

// oracle example segments and their VLQ mappings string.
// build_mappings([...]) == "AAAA,KAAI,IAAK;AACT,EAAI;ACDJ,UAKG"
struct Seg {
    std::int32_t genLine, genCol, srcIdx, origLine, origCol;
};

constexpr Seg EXAMPLE_SEGS[]{
    {0, 0, 0, 0, 0}, {0, 5, 0, 0, 4}, {0, 9, 0, 0, 9}, {1, 0, 0, 1, 0},
    {1, 2, 0, 1, 4}, {2, 0, 1, 0, 0}, {2, 10, 1, 5, 3},
};
constexpr std::string_view EXAMPLE_MAPPINGS{"AAAA,KAAI,IAAK;AACT,EAAI;ACDJ,UAKG"};

void test_builder_generates_mappings() {
    MappingsBuilder b{};
    for (const auto& s : EXAMPLE_SEGS) {
        b.append(SourceMapState{
            .generatedLine = s.genLine,
            .generatedColumn = s.genCol,
            .sourceIndex = s.srcIdx,
            .originalLine = s.origLine,
            .originalColumn = s.origCol,
        });
    }
    check_eq_str(b.str(), EXAMPLE_MAPPINGS, "builder full example");
}

void test_append_mapping_first_no_comma() {
    // First mapping into an empty buffer emits no leading comma.
    std::string buf{};
    append_mapping(buf, SourceMapState{}, SourceMapState{});
    check_eq_str(buf, "AAAA", "append first mapping");
    // Second mapping on the same line prepends a comma.
    append_mapping(buf, SourceMapState{}, SourceMapState{.generatedColumn = 5, .originalColumn = 4});
    check_eq_str(buf, "AAAA,KAAI", "append second mapping (comma)");
}

void test_append_mapping_after_semicolon() {
    // After a ';' no comma is inserted (line start).
    std::string buf{"AAAA;"};
    append_mapping(buf, SourceMapState{.generatedColumn = 0}, SourceMapState{});
    check_eq_str(buf, "AAAA;AAAA", "append after semicolon (no comma)");
}

// ── mappings parsing ───────────────────────────────────────────────────────

void test_parse_roundtrips_builder() {
    auto r{parse_mappings(EXAMPLE_MAPPINGS, /*sourcesCount=*/2)};
    check_true(r.ok, "parse example ok");
    check_eq_int(static_cast<std::int64_t>(r.mappings.size()), std::size(EXAMPLE_SEGS),
                 "parse example count");
    if (r.mappings.size() == std::size(EXAMPLE_SEGS)) {
        for (std::size_t i{0}; i < r.mappings.size(); ++i) {
            const Mapping& m{r.mappings[i]};
            const Seg& s{EXAMPLE_SEGS[i]};
            check_eq_int(m.generated.line, s.genLine, std::format("parse[{}].genLine", i));
            check_eq_int(m.generated.column, s.genCol, std::format("parse[{}].genCol", i));
            check_eq_int(m.sourceIndex, s.srcIdx, std::format("parse[{}].srcIdx", i));
            check_eq_int(m.original.line, s.origLine, std::format("parse[{}].origLine", i));
            check_eq_int(m.original.column, s.origCol, std::format("parse[{}].origCol", i));
        }
    }
}

void test_parse_single_mapping() {
    auto r{parse_mappings("AAAA", 1)};
    check_true(r.ok && r.mappings.size() == 1, "parse single ok");
    if (r.mappings.size() == 1) {
        const Mapping& m{r.mappings[0]};
        check_true(m.generated.line == 0 && m.generated.column == 0 && m.sourceIndex == 0 &&
                       m.original.line == 0 && m.original.column == 0,
                   "parse single values");
    }
}

void test_parse_with_names() {
    // 5-field mapping "AAAAA": all deltas 0, name index 0.
    auto r{parse_mappings("AAAAA", 1, /*allowNames=*/true)};
    check_true(r.ok && r.mappings.size() == 1, "parse names ok");
    if (r.mappings.size() == 1) {
        check_eq_int(r.mappings[0].nameIndex, 0, "parse name index");
    }
}

void test_parse_skips_one_field_segment() {
    // A lone generated-column field (no source info) is ignored per spec.
    auto r{parse_mappings("A", 1)};
    check_true(r.ok && r.mappings.empty(), "parse 1-field skipped");
}

void test_parse_multi_line_semicolons() {
    // Two empty lines then a mapping: ";;" advances generated line to 2.
    auto r{parse_mappings(";;AAAA", 1)};
    check_true(r.ok && r.mappings.size() == 1, "parse semicolons ok");
    if (r.mappings.size() == 1) {
        check_eq_int(r.mappings[0].generated.line, 2, "parse semicolons genLine");
    }
}

void test_parse_error_invalid_source_index() {
    // source index 0 with sourcesCount=0 is fine; but delta pushing it >= count
    // must fail. "AKAA" => genCol 0, srcIdx +5 (out of a 1-source map).
    auto r{parse_mappings("AKAA", /*sourcesCount=*/1)};
    check_true(!r.ok, "parse invalid source index fails");
    check_eq_str(r.error, "Invalid source index value", "parse invalid source index msg");
}

// ── find ───────────────────────────────────────────────────────────────────

void test_find_mapping() {
    auto r{parse_mappings(EXAMPLE_MAPPINGS, 2)};
    check_true(r.ok, "find: parse ok");
    // referenceFind semantics: last mapping with generated <= (line,col) on the
    // same generated line.
    // Line 0 has generated cols {0,5,9}.
    const Mapping* m{find_mapping(r.mappings, 0, 7)};
    check_true(m != nullptr && m->generated.column == 5, "find (0,7) -> col 5");
    m = find_mapping(r.mappings, 0, 5);
    check_true(m != nullptr && m->generated.column == 5, "find (0,5) exact -> col 5");
    m = find_mapping(r.mappings, 0, 100);
    check_true(m != nullptr && m->generated.column == 9, "find (0,100) -> col 9");
    m = find_mapping(r.mappings, 0, 4);
    check_true(m != nullptr && m->generated.column == 0, "find (0,4) -> col 0");
    // Line 1 has generated cols {0,2}.
    m = find_mapping(r.mappings, 1, 3);
    check_true(m != nullptr && m->generated.line == 1 && m->generated.column == 2,
               "find (1,3) -> line1 col2");
    // A line with no mappings at/below returns null when column precedes all.
    m = find_mapping(r.mappings, 5, 0);
    check_true(m == nullptr, "find (5,0) -> null (no such line)");
}

// ── SourceMap JSON ─────────────────────────────────────────────────────────

void test_sourcemap_to_json() {
    SourceMap sm{};
    sm.sources = {"a.js"};
    sm.names = {};
    sm.mappings = "AAAA";
    check_eq_str(sm.to_json(),
                 "{\"version\":3,\"sources\":[\"a.js\"],\"names\":[],\"mappings\":\"AAAA\"}",
                 "sourcemap minimal json");
}

void test_sourcemap_to_json_full() {
    SourceMap sm{};
    sm.file = "out.js";
    sm.sourceRoot = "/src";
    sm.sources = {"a.ts", "b.ts"};
    sm.sourcesContent = {std::string{"let a=1;"}, std::nullopt};
    sm.names = {"a", "b"};
    sm.mappings = "AAAA,KAAI";
    check_eq_str(
        sm.to_json(),
        "{\"version\":3,\"file\":\"out.js\",\"sourceRoot\":\"/src\","
        "\"sources\":[\"a.ts\",\"b.ts\"],\"sourcesContent\":[\"let a=1;\",null],"
        "\"names\":[\"a\",\"b\"],\"mappings\":\"AAAA,KAAI\"}",
        "sourcemap full json");
}

void test_sourcemap_json_escaping() {
    SourceMap sm{};
    sm.sources = {"a\"b\\c\n"};
    sm.mappings = "";
    check_eq_str(sm.to_json(),
                 "{\"version\":3,\"sources\":[\"a\\\"b\\\\c\\n\"],\"names\":[],\"mappings\":\"\"}",
                 "sourcemap json escaping");
}

// ── synthesis (finalize_pieces) ────────────────────────────────────────────

void test_finalize_passthrough() {
    // A single shift crosses no boundary: output is exact concatenation.
    // oracle: oracle2.py CASE_A_PASSTHROUGH
    std::string_view prefix{"{\"version\":3,\"sources\":[\"a.js\"],\"mappings\":\""};
    std::string_view mappings{"AAAA,KAAI,IAAK;AACT,EAAI"};
    std::string_view suffix{"\"}"};
    SourceMapShift shifts[]{{{0, 0}, {0, 0}}};
    std::string expected{std::string{prefix} + std::string{mappings} + std::string{suffix}};
    check_eq_str(finalize_pieces(prefix, mappings, suffix, shifts), expected,
                 "finalize passthrough");
}

void test_finalize_shift() {
    // Two shifts: crossing the second (before col 4 -> after col 7, delta +3)
    // re-encodes the second segment's generated-column delta from "K"(5) to
    // "Q"(8). oracle: oracle2.py CASE_B_SHIFT
    std::string_view prefix{"{\"version\":3,\"sources\":[\"a.js\"],\"mappings\":\""};
    std::string_view mappings{"AAAA,KAAI,IAAK;AACT,EAAI"};
    std::string_view suffix{"\"}"};
    SourceMapShift shifts[]{{{0, 0}, {0, 0}}, {{0, 4}, {0, 7}}};
    check_eq_str(
        finalize_pieces(prefix, mappings, suffix, shifts),
        "{\"version\":3,\"sources\":[\"a.js\"],\"mappings\":\"AAAA,QAAI,IAAK;AACT,EAAI\"}",
        "finalize shift +3");
}

void test_finalize_empty_fast_path() {
    // No mappings and no suffix: prefix returned verbatim.
    std::string_view prefix{"{\"version\":3}"};
    check_eq_str(finalize_pieces(prefix, "", "", std::span<const SourceMapShift>{}), prefix,
                 "finalize empty fast path");
}

}  // namespace

int main() {
    test_vlq_encode();
    test_vlq_decode();
    test_vlq_roundtrip();
    test_vlq_decode_multi();
    test_vlq_decode_invalid();

    test_builder_generates_mappings();
    test_append_mapping_first_no_comma();
    test_append_mapping_after_semicolon();

    test_parse_roundtrips_builder();
    test_parse_single_mapping();
    test_parse_with_names();
    test_parse_skips_one_field_segment();
    test_parse_multi_line_semicolons();
    test_parse_error_invalid_source_index();

    test_find_mapping();

    test_sourcemap_to_json();
    test_sourcemap_to_json_full();
    test_sourcemap_json_escaping();

    test_finalize_passthrough();
    test_finalize_shift();
    test_finalize_empty_fast_path();

    if (gFailures > MAX_FAILURE_PRINTS) {
        std::println("  ... {} more failures not shown", gFailures - MAX_FAILURE_PRINTS);
    }
    std::println("test_sourcemap: {} checks, {} failures", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
