#!/usr/bin/env bun
// Regenerate C++ oracle vectors from Bun's vendored upstream JSON tests.
// Usage (repo root): bun modules/toml/tools/extract_json_oracles.mjs <bun-ref-root>
import { canonicalHashHex } from "../../../benchmarks/suites/config/canonical-hash.mjs";

const ref = process.argv[2];
if (!ref) throw new Error("usage: extract_json_oracles.mjs <bun-ref-root>");

const transpiler = new Bun.Transpiler({ loader: "ts", target: "bun" });
const encoder = new TextEncoder();

function evaluatePrefix(path, marker, expose) {
  const source = require("fs").readFileSync(path, "utf8");
  const prefix = source.slice(0, source.indexOf(marker)).replace(/^import .*$/gm, "");
  const js = transpiler.transformSync(prefix + `\nglobalThis.__mbunExtract = ${expose};\n`);
  new Function(js)();
  const value = globalThis.__mbunExtract;
  delete globalThis.__mbunExtract;
  return value;
}

function cppBytes(text) {
  const bytes = encoder.encode(text);
  let escaped = "";
  for (const byte of bytes) escaped += `\\x${byte.toString(16).padStart(2, "0")}`;
  return `std::string_view{"${escaped}", ${bytes.length}}`;
}

function hash(value) {
  return `0x${canonicalHashHex(value)}ULL`;
}

const suitePath = `${ref}/test/js/bun/jsonc/json-test-suite.test.ts`;
const { Y_VALID, N_INVALID, N_VALID_JSONC, I_IMPLEMENTATION_DEFINED } = evaluatePrefix(
  suitePath,
  'describe("JSONTestSuite"',
  "{Y_VALID,N_INVALID,N_VALID_JSONC,I_IMPLEMENTATION_DEFINED}",
);

const corpus = [];
for (const [name, source] of Y_VALID) corpus.push([name, source, 1, hash(JSON.parse(source))]);
for (const [name, source] of N_INVALID) corpus.push([name, source, 0, "0ULL"]);
for (const [name, source, expected] of N_VALID_JSONC) corpus.push([name, source, 1, hash(expected)]);
for (const [name, source] of I_IMPLEMENTATION_DEFINED) {
  try {
    corpus.push([name, source, 1, hash(JSON.parse(source))]);
  } catch {
    corpus.push([name, source, 2, "0ULL"]);
  }
}
if (corpus.length !== 318) throw new Error(`expected 318 corpus cases, got ${corpus.length}`);

let corpusOut = `// Generated by tools/extract_json_oracles.mjs from JSONTestSuite @ 1ef36fa.\n`;
corpusOut += `inline const std::array<OracleCase, 318> JSON_CORPUS_CASES{{\n`;
for (const [name, source, outcome, expected] of corpus) {
  corpusOut += `    OracleCase{${JSON.stringify(name)}, ${cppBytes(source)}, ${outcome}, ${expected}},\n`;
}
corpusOut += `}};\n`;
await Bun.write("modules/toml/tests/json_corpus_vectors.inc", corpusOut);

const fuzzPath = `${ref}/test/js/bun/jsonc/json-differential-fuzz.test.ts`;
const fuzz = evaluatePrefix(
  fuzzPath,
  "test(`differential fuzz:",
  "{Rng,genDocTokens,joinTokens,decorate,mutate}",
);
const SEED = 0x6a736f6e;
const rng = new fuzz.Rng(SEED);
const generated = [];
for (let i = 0; i < 400; i++) {
  const tokens = fuzz.genDocTokens(rng);
  const plain = fuzz.joinTokens(tokens, rng);
  const expected = JSON.parse(plain);
  generated.push([plain, hash(expected)]);
  generated.push([fuzz.decorate(tokens, rng), hash(expected)]);
}

const mutantRng = new fuzz.Rng((SEED ^ 0x9e3779b9) >>> 0);
const mutants = [];
let base = "";
for (let i = 0; i < 1500; i++) {
  if (i % 4 === 0) base = fuzz.joinTokens(fuzz.genDocTokens(mutantRng), mutantRng);
  const text = fuzz.mutate(base, mutantRng);
  try {
    mutants.push([text, 1, hash(JSON.parse(text))]);
  } catch {
    mutants.push([text, 0, "0ULL"]);
  }
}

let generatedOut = `// Generated from json-differential-fuzz.test.ts seed 0x6a736f6e.\n`;
generatedOut += `inline const std::array<FuzzCase, 800> JSON_GENERATED_CASES{{\n`;
for (const [source, expected] of generated) {
  generatedOut += `    FuzzCase{${cppBytes(source)}, true, ${expected}},\n`;
}
generatedOut += `}};\n`;

let mutantOut = `// Generated mutation corpus from json-differential-fuzz.test.ts.\n`;
mutantOut += `inline const std::array<FuzzCase, 1500> JSON_MUTANT_CASES{{\n`;
for (const [source, required, expected] of mutants) {
  mutantOut += `    FuzzCase{${cppBytes(source)}, ${required ? "true" : "false"}, ${expected}},\n`;
}
mutantOut += `}};\n`;
await Bun.write("modules/toml/tests/json_fuzz_generated_vectors.inc", generatedOut);
await Bun.write("modules/toml/tests/json_fuzz_mutant_vectors.inc", mutantOut);

console.log(`generated ${corpus.length} corpus, ${generated.length} generated, ${mutants.length} mutant vectors`);
