// test_bcrypt.cpp — mbun.crypto.bcrypt known-answer + roundtrip vectors.
//
// External vectors are the canonical jBCrypt / OpenBSD bcrypt test set
// (empty and "a" passwords at cost 6/8/10). verify() recomputes the digest
// and compares the checksum, so a pass proves the EksBlowfish schedule,
// Blowfish cipher, and base64 all match the reference.

import std;
import mbun.crypto;

namespace {

using namespace mbun::crypto;

int g_failed { 0 };

std::span<const std::uint8_t> bytes(std::string_view s) {
    return { reinterpret_cast<const std::uint8_t*>(s.data()), s.size() };
}

void check_verify(std::string_view pw, std::string_view stored, bool want) {
    const auto got { bcrypt::verify(bytes(pw), stored) };
    if (!got.has_value()) {
        ++g_failed;
        std::println("FAIL bcrypt.verify({:?}) : malformed hash {}", pw, stored);
        return;
    }
    if (*got != want) {
        ++g_failed;
        std::println("FAIL bcrypt.verify({:?}, {}) : got {} want {}", pw, stored, *got, want);
    }
}

}  // namespace

int main() {
    // Canonical jBCrypt / OpenBSD vectors.
    check_verify("", "$2a$06$DCq7YPn5Rq63x1Lad4cll.TV4S6ytwfsfvkgY8jIucDrjc8deX1s.", true);
    check_verify("", "$2a$10$k1wbIrmNyFAPwPVPSVa/zecw2BCEnBwVS2GbrmgzxFUOqW9dk4TCW", true);
    check_verify("a", "$2a$06$m0CrhHm10qJ3lXRY.5zDGO3rS2KdeeWLuGmsfGlMfOxih58VYVfxe", true);
    check_verify("a", "$2a$08$cfcvVd2aQ8CMvoMpP2EBfeodLEkkFJ9umNEfPD18.hUF62qqlC/V.", true);

    // Wrong password must fail.
    check_verify("b", "$2a$06$m0CrhHm10qJ3lXRY.5zDGO3rS2KdeeWLuGmsfGlMfOxih58VYVfxe", false);
    check_verify("", "$2a$06$m0CrhHm10qJ3lXRY.5zDGO3rS2KdeeWLuGmsfGlMfOxih58VYVfxe", false);

    // Roundtrip with a freshly generated salt + explicit salt.
    {
        const std::string h { bcrypt::hash_random(bytes("correct horse"), 5) };
        check_verify("correct horse", h, true);
        check_verify("Correct horse", h, false);
        if (!h.starts_with("$2b$05$")) {
            ++g_failed;
            std::println("FAIL bcrypt.hash_random prefix: {}", h);
        }
    }

    // Fixed-salt hash reproducibility.
    {
        std::array<std::uint8_t, 16> salt {};
        for (std::size_t i { 0 }; i < 16; ++i) { salt[i] = static_cast<std::uint8_t>(i); }
        const std::string a { bcrypt::hash(bytes("hunter2"), 6, salt) };
        const std::string b { bcrypt::hash(bytes("hunter2"), 6, salt) };
        if (a != b) {
            ++g_failed;
            std::println("FAIL bcrypt deterministic: {} != {}", a, b);
        }
        check_verify("hunter2", a, true);
    }

    // Bun cross-version compat: passwords >72 bytes are SHA-512 pre-hashed to
    // 64 raw bytes before bcrypt. Hash generated by Bun 1.2.4 for "hello"×100.
    {
        std::string secret;
        for (int i { 0 }; i < 100; ++i) { secret += "hello"; }
        CryptoHasher h { DigestAlgo::Sha512 };
        h.update(bytes(secret));
        const std::vector<std::uint8_t> digest { h.digest() };
        check_verify(std::string_view { reinterpret_cast<const char*>(digest.data()), digest.size() },
                     "$2b$10$PsJ3/W82mzNJoP0rSblfvet2ab9jZg2aH7tIxr1B8uFLJwuWk/jTi", true);
    }

    if (g_failed == 0) {
        std::println("bcrypt: all vectors passed");
        return 0;
    }
    std::println("bcrypt: {} FAILED", g_failed);
    return 1;
}
