// entry_points.cppm — mbun.bundler.entry_points: entry-point records.
//
// Port of the linker-graph EntryPoint row + Kind enum (LinkerGraph.rs
// `entry_point`) and the FallbackEntryPoint code-buffer generator
// (entry_points.rs). The generator's real transpile round-trip (print → parse →
// link) is DEFERRED(S-bundler); we keep the string-assembly that produces the
// synthetic entry source.
// ref: .mbun/bun-ref/src/bundler/entry_points.rs, LinkerGraph.rs.
export module mbun.bundler.entry_points;

import std;
import mbun.bundler.index;
import mbun.bundler.source;
import mbun.bundler.options;

export namespace mbun::bundler {

// EntryPoint::Kind (LinkerGraph.rs).
enum class EntryPointKind : std::uint8_t {
    None = 0,  // default
    UserSpecified = 1,
    DynamicImport = 2,
    Html = 3,
};
constexpr bool entry_kind_is_entry_point(EntryPointKind k) { return k != EntryPointKind::None; }
constexpr bool entry_kind_is_user_specified(EntryPointKind k) {
    return k == EntryPointKind::UserSpecified;
}
constexpr bool entry_kind_is_server(EntryPointKind k) {
    return k == EntryPointKind::UserSpecified;
}
constexpr OutputKind entry_kind_output_kind(EntryPointKind k) {
    return k == EntryPointKind::UserSpecified ? OutputKind::EntryPoint : OutputKind::Chunk;
}

// EntryPoint row (LinkerGraph.rs::entry_point::EntryPoint).
struct EntryPoint {
    std::string outputPath;  // bun: RawSlice<u8>
    IndexInt sourceIndex { 0 };
    bool outputPathWasAutoGenerated { false };
};

// FallbackEntryPoint (entry_points.rs) — synthetic wrapper entry.
struct FallbackEntryPoint {
    Source source;
    std::string builtCode;

    // entry_points.rs::generate — assembles
    //   import * as EntryPoint from '<input>'; import boot from 'framework';
    //   boot(EntryPoint);
    // then (in bun) round-trips it through the parser/linker. The round-trip is
    // DEFERRED(S-bundler); we produce the synthetic source verbatim.
    void generate(std::string_view inputPath) {
        std::string code;
        code.reserve(inputPath.size() + 96);
        code += "import * as EntryPoint from '";
        code += inputPath;
        code += "';\nimport boot from 'framework';\nboot(EntryPoint);\n";
        source = Source::init_path_string(inputPath, code);
    }
};

}  // namespace mbun::bundler
