// test_glob.cpp — T2.9 mbun.glob (Bun.Glob.match equivalent) test suite.
//
// Test vectors are extracted verbatim from bun's original test suite
// (assertion semantics preserved, see AGENTS.md TDD rules):
//   - .mbun/bun-ref/test/js/bun/glob/match.test.ts
//       every static `expect(new Glob(p).match(s))` / `expect(glob.match(s))`
//       assertion (script-extracted, 1460 vectors); JS string literals are
//       decoded to UTF-16 code units and re-encoded as WTF-8 (paired
//       surrogates combine, lone surrogates keep 3-byte encodings), exactly
//       the byte sequences Bun hands to its matcher.
//   - .mbun/bun-ref/test/fixtures/glob/{filelist.txt,matched-0..9.txt}
//       embedded byte-exact in tests/glob_match_fixtures.inc for the
//       fixture-driven part of test("braces"); the JS split("\n") semantics
//       (trailing empty piece kept) are replicated below.
//   - dynamically-built patterns (Buffer.alloc / "a/".repeat(100)) from
//       test("deeply nested braces do not overflow depth counters") and
//       test("trailing globstar patterns") are hand-ported below with the
//       same construction.
//
// Platform note: test("trailing globstar patterns") asserts
// `new Glob("foo/**").match("foo\\bar")` is true on windows / false on posix
// (path separator is platform-native). The posix branch is asserted here; the
// windows expectation is the same vector with `true` under _WIN32.
//
// Intentionally skipped (registered per test-vector-extraction SOP):
//   - SKIPPED(S1) match.test.ts > test("invalid input"): JS argument-type
//     errors (match(null/true/{}) throws) — Bun.Glob API layer, not matcher
//     logic; covered when bun:test runner lands (T3.4).
//   - SKIPPED(S1) scan.test.ts (whole file): Glob.scan over real
//     directories (fs + cwd + symlink behavior).
//   - SKIPPED(S1) stress.test.ts (whole file): scan stress / GC pressure.
//   - SKIPPED(S1) leak.test.ts (whole file): RSS leak thresholds on scan.
//   - SKIPPED(S1) proto.test.ts (whole file): JS prototype/constructor
//     surface of the Bun.Glob class.
//   - SKIPPED(S1) path-length.test.ts (whole file): ENAMETOOLONG fs errors.
//   - match.test.ts > test("WTF"): entirely commented out upstream (no
//     assertions to port).
//   - match.test.ts > test("braces") line 127: `expect(glob.match(...))`
//     carries no matcher — a no-op assertion in bun:test, so no vector.
import std;
import mbun.glob;

namespace {

using mbun::glob::match;

int gChecks{0};
int gFailures{0};
constexpr int MAX_FAILURE_PRINTS{25};

void report_failure(std::string_view what) {
    ++gFailures;
    if (gFailures <= MAX_FAILURE_PRINTS) {
        std::println("  FAIL {}", what);
    }
}

void check_match(std::string_view pattern, std::string_view path, bool expected,
                 std::string_view src) {
    ++gChecks;
    bool actual{match(pattern, path)};
    if (actual != expected) {
        report_failure(std::format("[{}] match(\"{}\", \"{}\") = {}, expected {}", src, pattern,
                                   path, actual, expected));
    }
}

struct MatchVector {
    const char* pattern;
    const char* path;
    bool expected;
};

// clang-format off
constexpr MatchVector kMatchVectors[]{
    // source: test/js/bun/glob/match.test.ts > test("single wildcard")
    {"*", "foo", true},
    {"*", "lmao.ts", true},
    {"*", "", true},
    {"*", "   ", true},
    {"*", "*", true},
    {"*.ts", "foo.ts", true},
    {"*.ts", ".ts", true},
    {"*.ts", "", false},
    {"*.ts", "bar.tsx", false},
    {"*.ts", "foo/bar.ts", false},
    {"*.ts", "foo/bar/baz.ts", false},
    {"src/*/*.ts", "src/foo/bar.ts", true},
    {"src/*/*.ts", "src/bar.ts", false},
    {"src/**/hehe.ts", "src/foo/baz/lol/hehe.ts", true},
    // source: test/js/bun/glob/match.test.ts > test("double wildcard")
    {"**", "", true},
    {"**", "nice/wow/great/foo.ts", true},
    {"foo/**/bar", "", false},
    {"foo/**/bar", "foo/lmao/lol/bar", true},
    {"foo/**/bar", "foo/lmao/lol/haha/wtf/nice/bar", true},
    {"foo/**/bar", "foo/bar", true},
    {"src/**/*.ts", "src/foo/bar/baz/nice.ts", true},
    {"src/**/*.ts", "src/foo/bar/nice.ts", true},
    {"src/**/*.ts", "src/nice.ts", true},
    {"src/foo/*/bar/**/*.ts", "src/foo/nice/bar/baz/lmao.ts", true},
    {"src/foo/*/bar/**/*.ts", "src/foo/nice/bar/baz/lmao.ts", true},
    // source: test/js/bun/glob/match.test.ts > test("comma inside a bracket class inside braces is not a branch separator")
    {"x.{ts,[,]foo}", "x.,foo", true},
    {"x.{ts,[,]foo}", "x.]foo", false},
    {"x.{ts,[,]foo}", "x.ts", true},
    // source: test/js/bun/glob/match.test.ts > test("no early globstar lock-in")
    {"**/*abc*", "a/abc", true},
    {"**/*.js", "a/b.c/c.js", true},
    {"/**/*a", "/a/a", true},
    {"**/*.js", "a/b.c/c.js", true},
    {"**/**/*.js", "a/b.c/c.js", true},
    {"a/**/*.d", "a/b/c.d", true},
    {"a/**/*.d", "a/.b/c.d", true},
    {"**/*/**", "a/b/c", true},
    {"**/*/c.js", "a/b/c.js", true},
    // source: test/js/bun/glob/match.test.ts > test("braces")
    {"index.{ts,tsx,js,jsx}", "index.ts", true},
    {"index.{ts,tsx,js,jsx}", "index.tsx", true},
    {"index.{ts,tsx,js,jsx}", "index.js", true},
    {"index.{ts,tsx,js,jsx}", "index.jsx", true},
    {"index.{ts,tsx,js,jsx}", "index.jsxxxxxxxx", false},
    {"foo{bar,b*z}", "foobar", true},
    {"foo{bar,b*z}", "foobuzz", true},
    {"foo{bar,b*z}", "foobarz", true},
    {"{a}/{b}/", "a/b/", true},
    {"{a,{d,e}b}/c", "a/c", true},
    {"{**/a,**/b}", "b", true},
    // source: test/js/bun/glob/match.test.ts > test("nested braces")
    {"a{b,c{d,e}}f", "abf", true},
    {"a{b,c{d,e}}f", "acdf", true},
    {"a{b,c{d,e}}f", "acef", true},
    {"x{1,2{3,4}}y", "x1y", true},
    {"x{1,2{3,4}}y", "x23y", true},
    {"x{1,2{3,4}}y", "x24y", true},
    {"a{b,c{d,e},f}g", "abg", true},
    {"a{b,c{d,e},f}g", "acdg", true},
    {"a{b,c{d,e},f}g", "aceg", true},
    {"a{b,c{d,e},f}g", "afg", true},
    {"1{2,3{4,5{6,7}}}8", "128", true},
    {"1{2,3{4,5{6,7}}}8", "1348", true},
    {"1{2,3{4,5{6,7}}}8", "13568", true},
    {"1{2,3{4,5{6,7}}}8", "13578", true},
    {"{a,b{c,d{e,f{g,h}}}}i", "ai", true},
    {"{a,b{c,d{e,f{g,h}}}}i", "bci", true},
    {"{a,b{c,d{e,f{g,h}}}}i", "bdei", true},
    {"{a,b{c,d{e,f{g,h}}}}i", "bdfgi", true},
    {"{a,b{c,d{e,f{g,h}}}}i", "bdfhi", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vw7", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vxy7", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vxz17", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vxz237", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vxz2457", true},
    {"v{w,x{y,z{1,2{3,4{5,6}}}}}7", "vxz2467", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "abn", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "acdn", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "acefn", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "aceghn", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "acegijn", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "acegikln", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m}}}}}}n", "acegikmn", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "12g", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "134g", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "1356g", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "13578g", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "13579ag", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "13579bcg", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "13579bdeg", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f}}}}}}}g", "13579bdfg", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "pq7", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prs7", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtu7", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvw7", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvxy7", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvxz17", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvxz237", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvxz2457", true},
    {"p{q,r{s,t{u,v{w,x{y,z{1,2{3,4{5,6}}}}}}}}7", "prtvxz2467", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "abt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acdt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "aceft", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "aceght", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegijt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegiklt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegikmnt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegikmopt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegikmoqrt", true},
    {"a{b,c{d,e{f,g{h,i{j,k{l,m{n,o{p,q{r,s}}}}}}}}}t", "acegikmoqst", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "12m", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "134m", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "1356m", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13578m", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579am", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bcm", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bdem", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bdfgm", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bdfhim", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bdfhjkm", true},
    {"1{2,3{4,5{6,7{8,9{a,b{c,d{e,f{g,h{i,j{k,l}}}}}}}}}}m", "13579bdfhjlm", true},
    {"{a,{b,c}}", "a", true},
    {"{a,{b,c}}", "b", true},
    {"{a,{b,c}}", "c", true},
    {"{a,b{}}", "a", true},
    {"{a,b{}}", "b", true},
    {"{a,b{,c{{}}}}d", "ad", true},
    {"{a,b{,c{{}}}}d", "bcd", true},
    {"{{a,b},c}", "a", true},
    {"{{a,b},c}", "b", true},
    {"{{a,b},c}", "c", true},
    {"{a,b{c,d{}}}e", "ae", true},
    {"{a,b{c,d{}}}e", "bce", true},
    {"{a,b{c,d{}}}e", "bde", true},
    // source: test/js/bun/glob/match.test.ts > test("deeply nested braces do not overflow depth counters")
    // source: test/js/bun/glob/match.test.ts > test("non ascii")
    {"\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.{ts,tsx,js,jsx}", "\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.ts", true},
    {"\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.{ts,tsx,js,jsx}", "\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.tsx", true},
    {"\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.{ts,tsx,js,jsx}", "\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.js", true},
    {"\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.{ts,tsx,js,jsx}", "\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.jsx", true},
    {"\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.{ts,tsx,js,jsx}", "\xF0\x9F\x98\x8E/\xC2\xA2\xC2\xA3.jsxxxxxxxx", false},
    {"*\xC3\xA9*", "caf\xC3\xA9 noir", true},
    {"*\xC3\xA9*", "caf\xC3\xA9 noir", true},
    {"*\xC3\xA9*", "\xC3\xA9", true},
    {"*\xF0\x9F\x98\x8E", "\xF0\x9F\x98\x8E", true},
    {"*\xF0\x9F\x98\x8E", "\xC3\xAB\xC3\xAB\xC3\xAB\xC3\xAB\xC3\xAB\xC3\xAB\xF0\x9F\x98\x8E", true},
    {"caf*noir", "caf\xC3\xA9 noir", true},
    {"caf*noir", "caf\xC3\xA9 noir", true},
    {"caf*noir", "cafeenoir", true},
    {"F[\xC3\xAB\xC2\xA3" "a]", "F\xC3\xAB", true},
    {"F[\xC3\xAB\xC2\xA3" "a]", "F\xC2\xA3", true},
    {"F[\xC3\xAB\xC2\xA3" "a]", "Fa", true},
    {"\?\xC3\xABlmao", "\xC3\xABlmao", false},
    {"\?\xC3\xABlmao", "\xC3\xAB\xC3\xABlmao", true},
    {"\?\xC3\xABlmao", "f\xC3\xABlmao", true},
    {"\?\xC3\xABlmao", "lmao", false},
    {"F{\xC3\xAB,\xC2\xA3,a}", "F\xC3\xAB", true},
    {"F{\xC3\xAB,\xC2\xA3,a}", "F\xC2\xA3", true},
    {"F{\xC3\xAB,\xC2\xA3,a}", "Fa", true},
    {"F{\xC3\xAB,\xC2\xA3,a}", "Fb", false},
    {"F{\xC3\xAB,\xC2\xA3,a}", "F\xF0\x9F\x98\x8E", false},
    {"\\\xF0\x9F\x98\x8E", "\xF0\x9F\x98\x8E", true},
    {"\xED\xA0\xBD'", "lmao", false},
    {"\xED\xA0\x80\xED\xA0\x80", "lmao", false},
    {"*", "\xED\xA0\x80\xED\xA0\x80", true},
    {"hello/*/friends", "hello/\xED\xA0\x80\xED\xA0\x80/friends", true},
    {"*.{js,\xED\xA0\xBD'}", "runtime.node.pre.out.ts", false},
    {"*.{js,\xED\xA0\xBD'}", "runtime.node.pre.out.js", true},
    // source: test/js/bun/glob/match.test.ts > test("basic")
    {"abc", "abc", true},
    {"*", "abc", true},
    {"*", "", true},
    {"**", "", true},
    {"*c", "abc", true},
    {"*b", "abc", false},
    {"a*", "abc", true},
    {"b*", "abc", false},
    {"a*", "a", true},
    {"*a", "a", true},
    {"a*b*c*d*e*", "axbxcxdxe", true},
    {"a*b*c*d*e*", "axbxcxdxexxx", true},
    {"a*b\?c*x", "abxbbxdbxebxczzx", true},
    {"a*b\?c*x", "abxbbxdbxebxczzy", false},
    {"a/*/test", "a/foo/test", true},
    {"a/*/test", "a/foo/bar/test", false},
    {"a/**/test", "a/foo/test", true},
    {"a/**/test", "a/foo/bar/test", true},
    {"a/**/b/c", "a/foo/bar/b/c", true},
    {"a\\*b", "a*b", true},
    {"a\\*b", "axb", false},
    {"[abc]", "a", true},
    {"[abc]", "b", true},
    {"[abc]", "c", true},
    {"[abc]", "d", false},
    {"x[abc]x", "xax", true},
    {"x[abc]x", "xbx", true},
    {"x[abc]x", "xcx", true},
    {"x[abc]x", "xdx", false},
    {"x[abc]x", "xay", false},
    {"[\?]", "\?", true},
    {"[\?]", "a", false},
    {"[*]", "*", true},
    {"[*]", "a", false},
    {"[a-cx]", "a", true},
    {"[a-cx]", "b", true},
    {"[a-cx]", "c", true},
    {"[a-cx]", "d", false},
    {"[a-cx]", "x", true},
    {"[^abc]", "a", false},
    {"[^abc]", "b", false},
    {"[^abc]", "c", false},
    {"[^abc]", "d", true},
    {"[!abc]", "a", false},
    {"[!abc]", "b", false},
    {"[!abc]", "c", false},
    {"[!abc]", "d", true},
    {"[\\!]", "!", true},
    {"a*b*[cy]*d*e*", "axbxcxdxexxx", true},
    {"a*b*[cy]*d*e*", "axbxyxdxexxx", true},
    {"a*b*[cy]*d*e*", "axbxxxyxdxexxx", true},
    {"test.{jpg,png}", "test.jpg", true},
    {"test.{jpg,png}", "test.png", true},
    {"test.{j*g,p*g}", "test.jpg", true},
    {"test.{j*g,p*g}", "test.jpxxxg", true},
    {"test.{j*g,p*g}", "test.jxg", true},
    {"test.{j*g,p*g}", "test.jnt", false},
    {"test.{j*g,j*c}", "test.jnc", true},
    {"test.{jpg,p*g}", "test.png", true},
    {"test.{jpg,p*g}", "test.pxg", true},
    {"test.{jpg,p*g}", "test.pnt", false},
    {"test.{jpeg,png}", "test.jpeg", true},
    {"test.{jpeg,png}", "test.jpg", false},
    {"test.{jpeg,png}", "test.png", true},
    {"test.{jp\\,g,png}", "test.jp,g", true},
    {"test.{jp\\,g,png}", "test.jxg", false},
    {"test/{foo,bar}/baz", "test/foo/baz", true},
    {"test/{foo,bar}/baz", "test/bar/baz", true},
    {"test/{foo,bar}/baz", "test/baz/baz", false},
    {"test/{foo*,bar*}/baz", "test/foooooo/baz", true},
    {"test/{foo*,bar*}/baz", "test/barrrrr/baz", true},
    {"test/{*foo,*bar}/baz", "test/xxxxfoo/baz", true},
    {"test/{*foo,*bar}/baz", "test/xxxxbar/baz", true},
    {"test/{foo/**,bar}/baz", "test/bar/baz", true},
    {"test/{foo/**,bar}/baz", "test/bar/test/baz", false},
    {"*.txt", "some/big/path/to/the/needle.txt", false},
    {"some/**/needle.{js,tsx,mdx,ts,jsx,txt}", "some/a/bigger/path/to/the/crazy/needle.txt", true},
    {"some/**/{a,b,c}/**/needle.txt", "some/foo/a/bigger/path/to/the/crazy/needle.txt", true},
    {"some/**/{a,b,c}/**/needle.txt", "some/foo/d/bigger/path/to/the/crazy/needle.txt", false},
    {"a/{a{a,b},b}", "a/aa", true},
    {"a/{a{a,b},b}", "a/ab", true},
    {"a/{a{a,b},b}", "a/ac", false},
    {"a/{a{a,b},b}", "a/b", true},
    {"a/{a{a,b},b}", "a/c", false},
    {"a/{b,c[}]*}", "a/b", true},
    {"a/{b,c[}]*}", "a/c}xx", true},
    // source: test/js/bun/glob/match.test.ts > test("bash")
    {"a*", "*", false},
    {"a*", "**", false},
    {"a*", "\\*", false},
    {"a*", "a/*", false},
    {"a*", "b", false},
    {"a*", "bc", false},
    {"a*", "bcd", false},
    {"a*", "bdir/", false},
    {"a*", "Beware", false},
    {"a*", "a", true},
    {"a*", "ab", true},
    {"a*", "abc", true},
    {"\\a*", "*", false},
    {"\\a*", "**", false},
    {"\\a*", "\\*", false},
    {"\\a*", "a", true},
    {"\\a*", "a/*", false},
    {"\\a*", "abc", true},
    {"\\a*", "abd", true},
    {"\\a*", "abe", true},
    {"\\a*", "b", false},
    {"\\a*", "bb", false},
    {"\\a*", "bcd", false},
    {"\\a*", "bdir/", false},
    {"\\a*", "Beware", false},
    {"\\a*", "c", false},
    {"\\a*", "ca", false},
    {"\\a*", "cb", false},
    {"\\a*", "d", false},
    {"\\a*", "dd", false},
    {"\\a*", "de", false},
    // source: test/js/bun/glob/match.test.ts > test("bash directories")
    {"b*/", "*", false},
    {"b*/", "**", false},
    {"b*/", "\\*", false},
    {"b*/", "a", false},
    {"b*/", "a/*", false},
    {"b*/", "abc", false},
    {"b*/", "abd", false},
    {"b*/", "abe", false},
    {"b*/", "b", false},
    {"b*/", "bb", false},
    {"b*/", "bcd", false},
    {"b*/", "bdir/", true},
    {"b*/", "Beware", false},
    {"b*/", "c", false},
    {"b*/", "ca", false},
    {"b*/", "cb", false},
    {"b*/", "d", false},
    {"b*/", "dd", false},
    {"b*/", "de", false},
    // source: test/js/bun/glob/match.test.ts > test("bash escaping")
    {"\\^", "*", false},
    {"\\^", "**", false},
    {"\\^", "\\*", false},
    {"\\^", "a", false},
    {"\\^", "a/*", false},
    {"\\^", "abc", false},
    {"\\^", "abd", false},
    {"\\^", "abe", false},
    {"\\^", "b", false},
    {"\\^", "bb", false},
    {"\\^", "bcd", false},
    {"\\^", "bdir/", false},
    {"\\^", "Beware", false},
    {"\\^", "c", false},
    {"\\^", "ca", false},
    {"\\^", "cb", false},
    {"\\^", "d", false},
    {"\\^", "dd", false},
    {"\\^", "de", false},
    {"\\*", "*", true},
    {"\\*", "**", false},
    {"\\*", "a", false},
    {"\\*", "a/*", false},
    {"\\*", "abc", false},
    {"\\*", "abd", false},
    {"\\*", "abe", false},
    {"\\*", "b", false},
    {"\\*", "bb", false},
    {"\\*", "bcd", false},
    {"\\*", "bdir/", false},
    {"\\*", "Beware", false},
    {"\\*", "c", false},
    {"\\*", "ca", false},
    {"\\*", "cb", false},
    {"\\*", "d", false},
    {"\\*", "dd", false},
    {"\\*", "de", false},
    {"a\\*", "*", false},
    {"a\\*", "**", false},
    {"a\\*", "\\*", false},
    {"a\\*", "a", false},
    {"a\\*", "a/*", false},
    {"a\\*", "abc", false},
    {"a\\*", "abd", false},
    {"a\\*", "abe", false},
    {"a\\*", "b", false},
    {"a\\*", "bb", false},
    {"a\\*", "bcd", false},
    {"a\\*", "bdir/", false},
    {"a\\*", "Beware", false},
    {"a\\*", "c", false},
    {"a\\*", "ca", false},
    {"a\\*", "cb", false},
    {"a\\*", "d", false},
    {"a\\*", "dd", false},
    {"a\\*", "de", false},
    {"*q*", "aqa", true},
    {"*q*", "aaqaa", true},
    {"*q*", "*", false},
    {"*q*", "**", false},
    {"*q*", "\\*", false},
    {"*q*", "a", false},
    {"*q*", "a/*", false},
    {"*q*", "abc", false},
    {"*q*", "abd", false},
    {"*q*", "abe", false},
    {"*q*", "b", false},
    {"*q*", "bb", false},
    {"*q*", "bcd", false},
    {"*q*", "bdir/", false},
    {"*q*", "Beware", false},
    {"*q*", "c", false},
    {"*q*", "ca", false},
    {"*q*", "cb", false},
    {"*q*", "d", false},
    {"*q*", "dd", false},
    {"*q*", "de", false},
    {"\\**", "*", true},
    {"\\**", "**", true},
    {"\\**", "\\*", false},
    {"\\**", "a", false},
    {"\\**", "a/*", false},
    {"\\**", "abc", false},
    {"\\**", "abd", false},
    {"\\**", "abe", false},
    {"\\**", "b", false},
    {"\\**", "bb", false},
    {"\\**", "bcd", false},
    {"\\**", "bdir/", false},
    {"\\**", "Beware", false},
    {"\\**", "c", false},
    {"\\**", "ca", false},
    {"\\**", "cb", false},
    {"\\**", "d", false},
    {"\\**", "dd", false},
    {"\\**", "de", false},
    // source: test/js/bun/glob/match.test.ts > test("bash classes")
    {"a*[^c]", "*", false},
    {"a*[^c]", "**", false},
    {"a*[^c]", "\\*", false},
    {"a*[^c]", "a", false},
    {"a*[^c]", "a/*", false},
    {"a*[^c]", "abc", false},
    {"a*[^c]", "abd", true},
    {"a*[^c]", "abe", true},
    {"a*[^c]", "b", false},
    {"a*[^c]", "bb", false},
    {"a*[^c]", "bcd", false},
    {"a*[^c]", "bdir/", false},
    {"a*[^c]", "Beware", false},
    {"a*[^c]", "c", false},
    {"a*[^c]", "ca", false},
    {"a*[^c]", "cb", false},
    {"a*[^c]", "d", false},
    {"a*[^c]", "dd", false},
    {"a*[^c]", "de", false},
    {"a*[^c]", "baz", false},
    {"a*[^c]", "bzz", false},
    {"a*[^c]", "BZZ", false},
    {"a*[^c]", "beware", false},
    {"a*[^c]", "BewAre", false},
    {"a[X-]b", "a-b", true},
    {"a[X-]b", "aXb", true},
    {"[a-y]*[^c]", "*", false},
    {"[a-y]*[^c]", "a*", true},
    {"[a-y]*[^c]", "**", false},
    {"[a-y]*[^c]", "\\*", false},
    {"[a-y]*[^c]", "a", false},
    {"[a-y]*[^c]", "a123b", true},
    {"[a-y]*[^c]", "a123c", false},
    {"[a-y]*[^c]", "ab", true},
    {"[a-y]*[^c]", "a/*", false},
    {"[a-y]*[^c]", "abc", false},
    {"[a-y]*[^c]", "abd", true},
    {"[a-y]*[^c]", "abe", true},
    {"[a-y]*[^c]", "b", false},
    {"[a-y]*[^c]", "bd", true},
    {"[a-y]*[^c]", "bb", true},
    {"[a-y]*[^c]", "bcd", true},
    {"[a-y]*[^c]", "bdir/", true},
    {"[a-y]*[^c]", "Beware", false},
    {"[a-y]*[^c]", "c", false},
    {"[a-y]*[^c]", "ca", true},
    {"[a-y]*[^c]", "cb", true},
    {"[a-y]*[^c]", "d", false},
    {"[a-y]*[^c]", "dd", true},
    {"[a-y]*[^c]", "dd", true},
    {"[a-y]*[^c]", "dd", true},
    {"[a-y]*[^c]", "de", true},
    {"[a-y]*[^c]", "baz", true},
    {"[a-y]*[^c]", "bzz", true},
    {"[a-y]*[^c]", "bzz", true},
    {"[a-y]*[^c]", "BZZ", false},
    {"[a-y]*[^c]", "beware", true},
    {"[a-y]*[^c]", "BewAre", false},
    {"a\\*b/*", "a*b/ooo", true},
    {"a\\*\?/*", "a*b/ooo", true},
    {"a[b]c", "*", false},
    {"a[b]c", "**", false},
    {"a[b]c", "\\*", false},
    {"a[b]c", "a", false},
    {"a[b]c", "a/*", false},
    {"a[b]c", "abc", true},
    {"a[b]c", "abd", false},
    {"a[b]c", "abe", false},
    {"a[b]c", "b", false},
    {"a[b]c", "bb", false},
    {"a[b]c", "bcd", false},
    {"a[b]c", "bdir/", false},
    {"a[b]c", "Beware", false},
    {"a[b]c", "c", false},
    {"a[b]c", "ca", false},
    {"a[b]c", "cb", false},
    {"a[b]c", "d", false},
    {"a[b]c", "dd", false},
    {"a[b]c", "de", false},
    {"a[b]c", "baz", false},
    {"a[b]c", "bzz", false},
    {"a[b]c", "BZZ", false},
    {"a[b]c", "beware", false},
    {"a[b]c", "BewAre", false},
    {"a[\"b\"]c", "*", false},
    {"a[\"b\"]c", "**", false},
    {"a[\"b\"]c", "\\*", false},
    {"a[\"b\"]c", "a", false},
    {"a[\"b\"]c", "a/*", false},
    {"a[\"b\"]c", "abc", true},
    {"a[\"b\"]c", "abd", false},
    {"a[\"b\"]c", "abe", false},
    {"a[\"b\"]c", "b", false},
    {"a[\"b\"]c", "bb", false},
    {"a[\"b\"]c", "bcd", false},
    {"a[\"b\"]c", "bdir/", false},
    {"a[\"b\"]c", "Beware", false},
    {"a[\"b\"]c", "c", false},
    {"a[\"b\"]c", "ca", false},
    {"a[\"b\"]c", "cb", false},
    {"a[\"b\"]c", "d", false},
    {"a[\"b\"]c", "dd", false},
    {"a[\"b\"]c", "de", false},
    {"a[\"b\"]c", "baz", false},
    {"a[\"b\"]c", "bzz", false},
    {"a[\"b\"]c", "BZZ", false},
    {"a[\"b\"]c", "beware", false},
    {"a[\"b\"]c", "BewAre", false},
    {"a[\\\\b]c", "*", false},
    {"a[\\\\b]c", "**", false},
    {"a[\\\\b]c", "\\*", false},
    {"a[\\\\b]c", "a", false},
    {"a[\\\\b]c", "a/*", false},
    {"a[\\\\b]c", "abc", true},
    {"a[\\\\b]c", "abd", false},
    {"a[\\\\b]c", "abe", false},
    {"a[\\\\b]c", "b", false},
    {"a[\\\\b]c", "bb", false},
    {"a[\\\\b]c", "bcd", false},
    {"a[\\\\b]c", "bdir/", false},
    {"a[\\\\b]c", "Beware", false},
    {"a[\\\\b]c", "c", false},
    {"a[\\\\b]c", "ca", false},
    {"a[\\\\b]c", "cb", false},
    {"a[\\\\b]c", "d", false},
    {"a[\\\\b]c", "dd", false},
    {"a[\\\\b]c", "de", false},
    {"a[\\\\b]c", "baz", false},
    {"a[\\\\b]c", "bzz", false},
    {"a[\\\\b]c", "BZZ", false},
    {"a[\\\\b]c", "beware", false},
    {"a[\\\\b]c", "BewAre", false},
    {"a[\\b]c", "*", false},
    {"a[\\b]c", "**", false},
    {"a[\\b]c", "\\*", false},
    {"a[\\b]c", "a", false},
    {"a[\\b]c", "a/*", false},
    {"a[\\b]c", "abc", false},
    {"a[\\b]c", "abd", false},
    {"a[\\b]c", "abe", false},
    {"a[\\b]c", "b", false},
    {"a[\\b]c", "bb", false},
    {"a[\\b]c", "bcd", false},
    {"a[\\b]c", "bdir/", false},
    {"a[\\b]c", "Beware", false},
    {"a[\\b]c", "c", false},
    {"a[\\b]c", "ca", false},
    {"a[\\b]c", "cb", false},
    {"a[\\b]c", "d", false},
    {"a[\\b]c", "dd", false},
    {"a[\\b]c", "de", false},
    {"a[\\b]c", "baz", false},
    {"a[\\b]c", "bzz", false},
    {"a[\\b]c", "BZZ", false},
    {"a[\\b]c", "beware", false},
    {"a[\\b]c", "BewAre", false},
    {"a[b-d]c", "*", false},
    {"a[b-d]c", "**", false},
    {"a[b-d]c", "\\*", false},
    {"a[b-d]c", "a", false},
    {"a[b-d]c", "a/*", false},
    {"a[b-d]c", "abc", true},
    {"a[b-d]c", "abd", false},
    {"a[b-d]c", "abe", false},
    {"a[b-d]c", "b", false},
    {"a[b-d]c", "bb", false},
    {"a[b-d]c", "bcd", false},
    {"a[b-d]c", "bdir/", false},
    {"a[b-d]c", "Beware", false},
    {"a[b-d]c", "c", false},
    {"a[b-d]c", "ca", false},
    {"a[b-d]c", "cb", false},
    {"a[b-d]c", "d", false},
    {"a[b-d]c", "dd", false},
    {"a[b-d]c", "de", false},
    {"a[b-d]c", "baz", false},
    {"a[b-d]c", "bzz", false},
    {"a[b-d]c", "BZZ", false},
    {"a[b-d]c", "beware", false},
    {"a[b-d]c", "BewAre", false},
    {"a\?c", "*", false},
    {"a\?c", "**", false},
    {"a\?c", "\\*", false},
    {"a\?c", "a", false},
    {"a\?c", "a/*", false},
    {"a\?c", "abc", true},
    {"a\?c", "abd", false},
    {"a\?c", "abe", false},
    {"a\?c", "b", false},
    {"a\?c", "bb", false},
    {"a\?c", "bcd", false},
    {"a\?c", "bdir/", false},
    {"a\?c", "Beware", false},
    {"a\?c", "c", false},
    {"a\?c", "ca", false},
    {"a\?c", "cb", false},
    {"a\?c", "d", false},
    {"a\?c", "dd", false},
    {"a\?c", "de", false},
    {"a\?c", "baz", false},
    {"a\?c", "bzz", false},
    {"a\?c", "BZZ", false},
    {"a\?c", "beware", false},
    {"a\?c", "BewAre", false},
    {"*/man*/bash.*", "man/man1/bash.1", true},
    {"[^a-c]*", "*", true},
    {"[^a-c]*", "**", true},
    {"[^a-c]*", "a", false},
    {"[^a-c]*", "a/*", false},
    {"[^a-c]*", "abc", false},
    {"[^a-c]*", "abd", false},
    {"[^a-c]*", "abe", false},
    {"[^a-c]*", "b", false},
    {"[^a-c]*", "bb", false},
    {"[^a-c]*", "bcd", false},
    {"[^a-c]*", "bdir/", false},
    {"[^a-c]*", "Beware", true},
    {"[^a-c]*", "Beware", true},
    {"[^a-c]*", "c", false},
    {"[^a-c]*", "ca", false},
    {"[^a-c]*", "cb", false},
    {"[^a-c]*", "d", true},
    {"[^a-c]*", "dd", true},
    {"[^a-c]*", "de", true},
    {"[^a-c]*", "baz", false},
    {"[^a-c]*", "bzz", false},
    {"[^a-c]*", "BZZ", true},
    {"[^a-c]*", "beware", false},
    {"[^a-c]*", "BewAre", true},
    // source: test/js/bun/glob/match.test.ts > test("square braces")
    {"src/*.[tj]s", "src/foo.js", true},
    {"src/*.[tj]s", "src/foo.ts", true},
    {"foo/ba[rz].md", "foo/bar.md", true},
    {"foo/ba[rz].md", "foo/baz.md", true},
    // source: test/js/bun/glob/match.test.ts > test("bash wildmatch")
    {"a[]-]b", "aab", false},
    {"[ten]", "ten", false},
    {"]", "]", true},
    {"a[]-]b", "a-b", true},
    {"a[]-]b", "a]b", true},
    {"a[]]b", "a]b", true},
    {"a[\\]a\\-]b", "aab", true},
    {"t[a-g]n", "ten", true},
    {"t[^a-g]n", "ton", true},
    // source: test/js/bun/glob/match.test.ts > test("bash slashmatch")
    {"foo[/]bar", "foo/bar", true},
    {"f[^eiu][^eiu][^eiu][^eiu][^eiu]r", "foo-bar", true},
    // source: test/js/bun/glob/match.test.ts > test("bash extra_stars")
    {"a**c", "bbc", false},
    {"a**c", "abc", true},
    {"a**c", "bbd", false},
    {"a***c", "bbc", false},
    {"a***c", "abc", true},
    {"a***c", "bbd", false},
    {"a*****\?c", "bbc", false},
    {"a*****\?c", "abc", true},
    {"a*****\?c", "bbc", false},
    {"\?*****\?\?", "bbc", true},
    {"\?*****\?\?", "abc", true},
    {"*****\?\?", "bbc", true},
    {"*****\?\?", "abc", true},
    {"\?*****\?c", "bbc", true},
    {"\?*****\?c", "abc", true},
    {"\?***\?****c", "bbc", true},
    {"\?***\?****c", "abc", true},
    {"\?***\?****c", "bbd", false},
    {"\?***\?****\?", "bbc", true},
    {"\?***\?****\?", "abc", true},
    {"\?***\?****", "bbc", true},
    {"\?***\?****", "abc", true},
    {"*******c", "bbc", true},
    {"*******c", "abc", true},
    {"*******\?", "bbc", true},
    {"*******\?", "abc", true},
    {"a*cd**\?**\?\?k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?k***", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?***k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?***k**", "abcdecdhjk", true},
    {"a****c**\?**\?\?*****", "abcdecdhjk", true},
    // source: test/js/bun/glob/match.test.ts > test("stars")
    {"*.js", "a/b/c/z.js", false},
    {"*.js", "a/b/z.js", false},
    {"*.js", "a/z.js", false},
    {"*.js", "z.js", true},
    {"z*.js", "z.js", true},
    {"*/*", "a/z", true},
    {"*/z*.js", "a/z.js", true},
    {"a/z*.js", "a/z.js", true},
    {"*", "ab", true},
    {"*", "abc", true},
    {"f*", "bar", false},
    {"*r", "foo", false},
    {"b*", "foo", false},
    {"*", "foo/bar", false},
    {"*c", "abc", true},
    {"a*", "abc", true},
    {"a*c", "abc", true},
    {"*r", "bar", true},
    {"b*", "bar", true},
    {"f*", "foo", true},
    {"*abc*", "one abc two", true},
    {"a*b", "a         b", true},
    {"*a*", "foo", false},
    {"*a*", "bar", true},
    {"*abc*", "oneabctwo", true},
    {"*-bc-*", "a-b.c-d", false},
    {"*-*.*-*", "a-b.c-d", true},
    {"*-b*c-*", "a-b.c-d", true},
    {"*-b.c-*", "a-b.c-d", true},
    {"*.*", "a-b.c-d", true},
    {"*.*-*", "a-b.c-d", true},
    {"*.*-d", "a-b.c-d", true},
    {"*.c-*", "a-b.c-d", true},
    {"*b.*d", "a-b.c-d", true},
    {"a*.c*", "a-b.c-d", true},
    {"a-*.*-d", "a-b.c-d", true},
    {"*.*", "a.b", true},
    {"*.b", "a.b", true},
    {"a.*", "a.b", true},
    {"a.b", "a.b", true},
    {"**-bc-**", "a-b.c-d", false},
    {"**-**.**-**", "a-b.c-d", true},
    {"**-b**c-**", "a-b.c-d", true},
    {"**-b.c-**", "a-b.c-d", true},
    {"**.**", "a-b.c-d", true},
    {"**.**-**", "a-b.c-d", true},
    {"**.**-d", "a-b.c-d", true},
    {"**.c-**", "a-b.c-d", true},
    {"**b.**d", "a-b.c-d", true},
    {"a**.c**", "a-b.c-d", true},
    {"a-**.**-d", "a-b.c-d", true},
    {"**.**", "a.b", true},
    {"**.b", "a.b", true},
    {"a.**", "a.b", true},
    {"a.b", "a.b", true},
    {"*/*", "/ab", true},
    {".", ".", true},
    {"a/", "a/.b", false},
    {"/*", "/ab", true},
    {"/\?\?", "/ab", true},
    {"/\?b", "/ab", true},
    {"/*", "/cd", true},
    {"a", "a", true},
    {"a/.*", "a/.b", true},
    {"\?/\?", "a/b", true},
    {"a/**/j/**/z/*.md", "a/b/c/d/e/j/n/p/o/z/c.md", true},
    {"a/**/z/*.md", "a/b/c/d/e/z/c.md", true},
    {"a/b/c/*.md", "a/b/c/xyz.md", true},
    {"a/b/c/*.md", "a/b/c/xyz.md", true},
    {"a/*/z/.a", "a/b/z/.a", true},
    {"bz", "a/b/z/.a", false},
    {"a/**/c/*.md", "a/bb.bb/aa/b.b/aa/c/xyz.md", true},
    {"a/**/c/*.md", "a/bb.bb/aa/bb/aa/c/xyz.md", true},
    {"a/*/c/*.md", "a/bb.bb/c/xyz.md", true},
    {"a/*/c/*.md", "a/bb/c/xyz.md", true},
    {"a/*/c/*.md", "a/bbbb/c/xyz.md", true},
    {"*", "aaa", true},
    {"*", "ab", true},
    {"ab", "ab", true},
    {"*/*/*", "aaa", false},
    {"*/*/*", "aaa/bb/aa/rr", false},
    {"aaa*", "aaa/bba/ccc", false},
    {"aaa/*", "aaa/bba/ccc", false},
    {"aaa/*ccc", "aaa/bba/ccc", false},
    {"aaa/*z", "aaa/bba/ccc", false},
    {"*/*/*", "aaa/bbb", false},
    {"*/*jk*/*i", "ab/zzz/ejkl/hi", false},
    {"*/*/*", "aaa/bba/ccc", true},
    {"aaa/**", "aaa/bba/ccc", true},
    {"aaa/*", "aaa/bbb", true},
    {"*/*z*/*/*i", "ab/zzz/ejkl/hi", true},
    {"*j*i", "abzzzejklhi", true},
    {"*", "a", true},
    {"*", "b", true},
    {"*", "a/a", false},
    {"*", "a/a/a", false},
    {"*", "a/a/b", false},
    {"*", "a/a/a/a", false},
    {"*", "a/a/a/a/a", false},
    {"*/*", "a", false},
    {"*/*", "a/a", true},
    {"*/*", "a/a/a", false},
    {"*/*/*", "a", false},
    {"*/*/*", "a/a", false},
    {"*/*/*", "a/a/a", true},
    {"*/*/*", "a/a/a/a", false},
    {"*/*/*/*", "a", false},
    {"*/*/*/*", "a/a", false},
    {"*/*/*/*", "a/a/a", false},
    {"*/*/*/*", "a/a/a/a", true},
    {"*/*/*/*", "a/a/a/a/a", false},
    {"*/*/*/*/*", "a", false},
    {"*/*/*/*/*", "a/a", false},
    {"*/*/*/*/*", "a/a/a", false},
    {"*/*/*/*/*", "a/a/b", false},
    {"*/*/*/*/*", "a/a/a/a", false},
    {"*/*/*/*/*", "a/a/a/a/a", true},
    {"*/*/*/*/*", "a/a/a/a/a/a", false},
    {"a/*", "a", false},
    {"a/*", "a/a", true},
    {"a/*", "a/a/a", false},
    {"a/*", "a/a/a/a", false},
    {"a/*", "a/a/a/a/a", false},
    {"a/*/*", "a", false},
    {"a/*/*", "a/a", false},
    {"a/*/*", "a/a/a", true},
    {"a/*/*", "b/a/a", false},
    {"a/*/*", "a/a/a/a", false},
    {"a/*/*", "a/a/a/a/a", false},
    {"a/*/*/*", "a", false},
    {"a/*/*/*", "a/a", false},
    {"a/*/*/*", "a/a/a", false},
    {"a/*/*/*", "a/a/a/a", true},
    {"a/*/*/*", "a/a/a/a/a", false},
    {"a/*/*/*/*", "a", false},
    {"a/*/*/*/*", "a/a", false},
    {"a/*/*/*/*", "a/a/a", false},
    {"a/*/*/*/*", "a/a/b", false},
    {"a/*/*/*/*", "a/a/a/a", false},
    {"a/*/*/*/*", "a/a/a/a/a", true},
    {"a/*/a", "a", false},
    {"a/*/a", "a/a", false},
    {"a/*/a", "a/a/a", true},
    {"a/*/a", "a/a/b", false},
    {"a/*/a", "a/a/a/a", false},
    {"a/*/a", "a/a/a/a/a", false},
    {"a/*/b", "a", false},
    {"a/*/b", "a/a", false},
    {"a/*/b", "a/a/a", false},
    {"a/*/b", "a/a/b", true},
    {"a/*/b", "a/a/a/a", false},
    {"a/*/b", "a/a/a/a/a", false},
    {"*/**/a", "a", false},
    {"*/**/a", "a/a/b", false},
    {"*/**/a", "a/a", true},
    {"*/**/a", "a/a/a", true},
    {"*/**/a", "a/a/a/a", true},
    {"*/**/a", "a/a/a/a/a", true},
    {"*/", "a", false},
    {"*/*", "a", false},
    {"a/*", "a", false},
    {"*", "a/a", false},
    {"*/", "a/a", false},
    {"*/", "a/x/y", false},
    {"*/*", "a/x/y", false},
    {"a/*", "a/x/y", false},
    {"*", "a", true},
    {"*/", "a/", true},
    {"*{,/}", "a/", true},
    {"*/*", "a/a", true},
    {"a/*", "a/a", true},
    {"a/**/*.txt", "a.txt", false},
    {"a/**/*.txt", "a/x/y.txt", true},
    {"a/**/*.txt", "a/x/y/z", false},
    {"a/*.txt", "a.txt", false},
    {"a/*.txt", "a/b.txt", true},
    {"a/*.txt", "a/x/y.txt", false},
    {"a/*.txt", "a/x/y/z", false},
    {"a*.txt", "a.txt", true},
    {"a*.txt", "a/b.txt", false},
    {"a*.txt", "a/x/y.txt", false},
    {"a*.txt", "a/x/y/z", false},
    {"*.txt", "a.txt", true},
    {"*.txt", "a/b.txt", false},
    {"*.txt", "a/x/y.txt", false},
    {"*.txt", "a/x/y/z", false},
    {"a*", "a/b", false},
    {"a/**/b", "a/a/bb", false},
    {"a/**/b", "a/bb", false},
    {"*/**", "foo", false},
    {"**/", "foo/bar", false},
    {"**/*/", "foo/bar", false},
    {"*/*/", "foo/bar", false},
    {"**/..", "/home/foo/..", true},
    {"**/a", "a", true},
    {"**", "a/a", true},
    {"a/**", "a/a", true},
    {"a/**", "a/", true},
    {"**/", "a/a", false},
    {"**/", "a/a", false},
    {"*/**/a", "a/a", true},
    {"*/**", "foo/", true},
    {"**/*", "foo/bar", true},
    {"*/*", "foo/bar", true},
    {"*/**", "foo/bar", true},
    {"**/", "foo/bar/", true},
    {"**/*/", "foo/bar/", true},
    {"*/**", "foo/bar/", true},
    {"*/*/", "foo/bar/", true},
    {"*/foo", "bar/baz/foo", false},
    {"**/bar/*", "deep/foo/bar", false},
    {"*/bar/**", "deep/foo/bar/baz/x", false},
    {"/*", "ef", false},
    {"foo\?bar", "foo/bar", false},
    {"**/bar*", "foo/bar/baz", false},
    {"foo**bar", "foo/baz/bar", false},
    {"foo*bar", "foo/baz/bar", false},
    {"/*", "/ab", true},
    {"/*", "/cd", true},
    {"/*", "/ef", true},
    {"a/**/j/**/z/*.md", "a/b/j/c/z/x.md", true},
    {"a/**/j/**/z/*.md", "a/j/z/x.md", true},
    {"**/foo", "bar/baz/foo", true},
    {"**/bar/*", "deep/foo/bar/baz", true},
    {"**/bar/**", "deep/foo/bar/baz/", true},
    {"**/bar/*/*", "deep/foo/bar/baz/x", true},
    {"foo/**/**/bar", "foo/b/a/z/bar", true},
    {"foo/**/bar", "foo/b/a/z/bar", true},
    {"foo/**/**/bar", "foo/bar", true},
    {"foo/**/bar", "foo/bar", true},
    {"*/bar/**", "foo/bar/baz/x", true},
    {"foo/**/**/bar", "foo/baz/bar", true},
    {"foo/**/bar", "foo/baz/bar", true},
    {"**/foo", "XXX/foo", true},
    // source: test/js/bun/glob/match.test.ts > test("globstars")
    {"**/*.js", "a/b/c/d.js", true},
    {"**/*.js", "a/b/c.js", true},
    {"**/*.js", "a/b.js", true},
    {"a/b/**/*.js", "a/b/c/d/e/f.js", true},
    {"a/b/**/*.js", "a/b/c/d/e.js", true},
    {"a/b/c/**/*.js", "a/b/c/d.js", true},
    {"a/b/**/*.js", "a/b/c/d.js", true},
    {"a/b/**/*.js", "a/b/d.js", true},
    {"a/b/**/*.js", "a/d.js", false},
    {"a/b/**/*.js", "d.js", false},
    {"**c", "a/b/c", false},
    {"a/**c", "a/b/c", false},
    {"a/**z", "a/b/c", false},
    {"a/**b**/c", "a/b/c/b/c", false},
    {"a/b/c**/*.js", "a/b/c/d/e.js", false},
    {"a/**/b/**/c", "a/b/c/b/c", true},
    {"a/**b**/c", "a/aba/c", true},
    {"a/**b**/c", "a/b/c", true},
    {"a/b/c**/*.js", "a/b/c/d.js", true},
    {"a/**/*", "a", false},
    {"a/**/**/*", "a", false},
    {"a/**/**/**/*", "a", false},
    {"**/a", "a/", false},
    {"a/**/*", "a/", false},
    {"a/**/**/*", "a/", false},
    {"a/**/**/**/*", "a/", false},
    {"**/a", "a/b", false},
    {"a/**/j/**/z/*.md", "a/b/c/j/e/z/c.txt", false},
    {"a/**/b", "a/bb", false},
    {"**/a", "a/c", false},
    {"**/a", "a/b", false},
    {"**/a", "a/x/y", false},
    {"**/a", "a/b/c/d", false},
    {"**", "a", true},
    {"**/a", "a", true},
    {"**", "a/", true},
    {"**/a/**", "a/", true},
    {"a/**", "a/", true},
    {"a/**/**", "a/", true},
    {"**/a", "a/a", true},
    {"**", "a/b", true},
    {"*/*", "a/b", true},
    {"a/**", "a/b", true},
    {"a/**/*", "a/b", true},
    {"a/**/**/*", "a/b", true},
    {"a/**/**/**/*", "a/b", true},
    {"a/**/b", "a/b", true},
    {"**", "a/b/c", true},
    {"**/*", "a/b/c", true},
    {"**/**", "a/b/c", true},
    {"*/**", "a/b/c", true},
    {"a/**", "a/b/c", true},
    {"a/**/*", "a/b/c", true},
    {"a/**/**/*", "a/b/c", true},
    {"a/**/**/**/*", "a/b/c", true},
    {"**", "a/b/c/d", true},
    {"a/**", "a/b/c/d", true},
    {"a/**/*", "a/b/c/d", true},
    {"a/**/**/*", "a/b/c/d", true},
    {"a/**/**/**/*", "a/b/c/d", true},
    {"a/b/**/c/**/*.*", "a/b/c/d.e", true},
    {"a/**/f/*.md", "a/b/c/d/e/f/g.md", true},
    {"a/**/f/**/k/*.md", "a/b/c/d/e/f/g/h/i/j/k/l.md", true},
    {"a/b/c/*.md", "a/b/c/def.md", true},
    {"a/*/c/*.md", "a/bb.bb/c/ddd.md", true},
    {"a/**/f/*.md", "a/bb.bb/cc/d.d/ee/f/ggg.md", true},
    {"a/**/f/*.md", "a/bb.bb/cc/dd/ee/f/ggg.md", true},
    {"a/*/c/*.md", "a/bb/c/ddd.md", true},
    {"a/*/c/*.md", "a/bbbb/c/ddd.md", true},
    {"foo/bar/**/one/**/*.*", "foo/bar/baz/one/image.png", true},
    {"foo/bar/**/one/**/*.*", "foo/bar/baz/one/two/image.png", true},
    {"foo/bar/**/one/**/*.*", "foo/bar/baz/one/two/three/image.png", true},
    {"a/b/**/f", "a/b/c/d/", false},
    {"**", "a", true},
    {"**", "a/", true},
    {"a/**", "a/", true},
    {"**", "a/b/c/d", true},
    {"**", "a/b/c/d/", true},
    {"**/**", "a/b/c/d/", true},
    {"**/b/**", "a/b/c/d/", true},
    {"a/b/**", "a/b/c/d/", true},
    {"a/b/**/", "a/b/c/d/", true},
    {"a/b/**/c/**/", "a/b/c/d/", true},
    {"a/b/**/c/**/d/", "a/b/c/d/", true},
    {"a/b/**/**/*.*", "a/b/c/d/e.f", true},
    {"a/b/**/*.*", "a/b/c/d/e.f", true},
    {"a/b/**/c/**/d/*.*", "a/b/c/d/e.f", true},
    {"a/b/**/d/**/*.*", "a/b/c/d/e.f", true},
    {"a/b/**/d/**/*.*", "a/b/c/d/g/e.f", true},
    {"a/b/**/d/**/*.*", "a/b/c/d/g/g/e.f", true},
    {"a/b-*/**/z.js", "a/b-c/z.js", true},
    {"a/b-*/**/z.js", "a/b-c/d/e/z.js", true},
    {"*/*", "a/b", true},
    {"a/b/c/*.md", "a/b/c/xyz.md", true},
    {"a/*/c/*.md", "a/bb.bb/c/xyz.md", true},
    {"a/*/c/*.md", "a/bb/c/xyz.md", true},
    {"a/*/c/*.md", "a/bbbb/c/xyz.md", true},
    {"**/*", "a/b/c", true},
    {"**/**", "a/b/c", true},
    {"*/**", "a/b/c", true},
    {"a/**/j/**/z/*.md", "a/b/c/d/e/j/n/p/o/z/c.md", true},
    {"a/**/z/*.md", "a/b/c/d/e/z/c.md", true},
    {"a/**/c/*.md", "a/bb.bb/aa/b.b/aa/c/xyz.md", true},
    {"a/**/c/*.md", "a/bb.bb/aa/bb/aa/c/xyz.md", true},
    {"a/**/j/**/z/*.md", "a/b/c/j/e/z/c.txt", false},
    {"a/b/**/c{d,e}/**/xyz.md", "a/b/c/xyz.md", false},
    {"a/b/**/c{d,e}/**/xyz.md", "a/b/d/xyz.md", false},
    {"a/**/", "a/b", false},
    {"a/**/", "a/b/c/d", false},
    {"a/**/", "a/bb", false},
    {"a/**/", "a/cb", false},
    {"/**", "/a/b", true},
    {"**/*", "a.b", true},
    {"**/*", "a.js", true},
    {"**/*.js", "a.js", true},
    {"**/*.js", "a/a.js", true},
    {"**/*.js", "a/a/b.js", true},
    {"a/**/b", "a/b", true},
    {"a/**b", "a/b", true},
    {"**/*.md", "a/b.md", true},
    {"**/*", "a/b/c.js", true},
    {"**/*", "a/b/c.txt", true},
    {"a/**/", "a/b/c/d/", true},
    {"**/*", "a/b/c/d/a.js", true},
    {"a/b/**/*.js", "a/b/c/z.js", true},
    {"a/b/**/*.js", "a/b/z.js", true},
    {"**/*", "ab", true},
    {"**/*", "ab/c", true},
    {"**/*", "ab/c/d", true},
    {"**/*", "abc.js", true},
    {"**/", "a", false},
    {"**/a/*", "a", false},
    {"**/a/*/*", "a", false},
    {"*/a/**", "a", false},
    {"a/**/*", "a", false},
    {"a/**/**/*", "a", false},
    {"**/", "a/b", false},
    {"**/b/*", "a/b", false},
    {"**/b/*/*", "a/b", false},
    {"b/**", "a/b", false},
    {"**/", "a/b/c", false},
    {"**/**/b", "a/b/c", false},
    {"**/b", "a/b/c", false},
    {"**/b/*/*", "a/b/c", false},
    {"b/**", "a/b/c", false},
    {"**/", "a/b/c/d", false},
    {"**/d/*", "a/b/c/d", false},
    {"b/**", "a/b/c/d", false},
    {"**", "a", true},
    {"**/**", "a", true},
    {"**/**/*", "a", true},
    {"**/**/a", "a", true},
    {"**/a", "a", true},
    {"**", "a/b", true},
    {"**/**", "a/b", true},
    {"**/**/*", "a/b", true},
    {"**/**/b", "a/b", true},
    {"**/b", "a/b", true},
    {"a/**", "a/b", true},
    {"a/**/*", "a/b", true},
    {"a/**/**/*", "a/b", true},
    {"**", "a/b/c", true},
    {"**/**", "a/b/c", true},
    {"**/**/*", "a/b/c", true},
    {"**/b/*", "a/b/c", true},
    {"**/b/**", "a/b/c", true},
    {"*/b/**", "a/b/c", true},
    {"a/**", "a/b/c", true},
    {"a/**/*", "a/b/c", true},
    {"a/**/**/*", "a/b/c", true},
    {"**", "a/b/c/d", true},
    {"**/**", "a/b/c/d", true},
    {"**/**/*", "a/b/c/d", true},
    {"**/**/d", "a/b/c/d", true},
    {"**/b/**", "a/b/c/d", true},
    {"**/b/*/*", "a/b/c/d", true},
    {"**/d", "a/b/c/d", true},
    {"*/b/**", "a/b/c/d", true},
    {"a/**", "a/b/c/d", true},
    {"a/**/*", "a/b/c/d", true},
    {"a/**/**/*", "a/b/c/d", true},
    // source: test/js/bun/glob/match.test.ts > test("utf8")
    {"\xE3\x83\x95*/**/*", "\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/aaa.js", true},
    {"\xE3\x83\x95\xE3\x82\xA9*/**/*", "\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/aaa.js", true},
    {"\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB*/**/*", "\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/aaa.js", true},
    {"\xE3\x83\x95*\xE3\x83\xAB*/**/*", "\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/aaa.js", true},
    {"\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/**/*", "\xE3\x83\x95\xE3\x82\xA9\xE3\x83\xAB\xE3\x83\x80/aaa.js", true},
    // source: test/js/bun/glob/match.test.ts > test("negation")
    {"!*", "abc", false},
    {"!abc", "abc", false},
    {"*!.md", "bar.md", false},
    {"foo!.md", "bar.md", false},
    {"\\!*!*.md", "foo!.md", false},
    {"\\!*!*.md", "foo!bar.md", false},
    {"*!*.md", "!foo!.md", true},
    {"\\!*!*.md", "!foo!.md", true},
    {"!*foo", "abc", true},
    {"!foo*", "abc", true},
    {"!xyz", "abc", true},
    {"*!*.*", "ba!r.js", true},
    {"*.md", "bar.md", true},
    {"*!*.*", "foo!.md", true},
    {"*!*.md", "foo!.md", true},
    {"*!.md", "foo!.md", true},
    {"*.md", "foo!.md", true},
    {"foo!.md", "foo!.md", true},
    {"*!*.md", "foo!bar.md", true},
    {"*b*.md", "foobar.md", true},
    {"a!!b", "a", false},
    {"a!!b", "aa", false},
    {"a!!b", "a/b", false},
    {"a!!b", "a!b", false},
    {"a!!b", "a!!b", true},
    {"a!!b", "a/!!/b", false},
    {"!a/b", "a/b", false},
    {"!a/b", "a", true},
    {"!a/b", "a.b", true},
    {"!a/b", "a/a", true},
    {"!a/b", "a/c", true},
    {"!a/b", "b/a", true},
    {"!a/b", "b/b", true},
    {"!a/b", "b/c", true},
    {"!abc", "abc", false},
    {"!!abc", "abc", true},
    {"!!!abc", "abc", false},
    {"!!!!abc", "abc", true},
    {"!!!!!abc", "abc", false},
    {"!!!!!!abc", "abc", true},
    {"!!!!!!!abc", "abc", false},
    {"!!!!!!!!abc", "abc", true},
    {"!*", "a", false},
    {"!*", "a.b", false},
    {"!*/*", "a/a", false},
    {"!*/*", "a/b", false},
    {"!*/*", "a/c", false},
    {"!*/*", "b/a", false},
    {"!*/*", "b/b", false},
    {"!*/*", "b/c", false},
    {"!*/b", "a/b", false},
    {"!*/b", "b/b", false},
    {"!*/c", "a/c", false},
    {"!*/c", "a/c", false},
    {"!*/c", "b/c", false},
    {"!*/c", "b/c", false},
    {"!*a*", "bar", false},
    {"!*a*", "fab", false},
    {"!a/*", "a/a", false},
    {"!a/*", "a/b", false},
    {"!a/*", "a/c", false},
    {"!f*b", "fab", false},
    {"!*", "a/a", true},
    {"!*", "a/b", true},
    {"!*", "a/c", true},
    {"!*", "b/a", true},
    {"!*", "b/b", true},
    {"!*", "b/c", true},
    {"!*/*", "a", true},
    {"!*/*", "a.b", true},
    {"!*/b", "a", true},
    {"!*/b", "a.b", true},
    {"!*/b", "a/a", true},
    {"!*/b", "a/c", true},
    {"!*/b", "b/a", true},
    {"!*/b", "b/c", true},
    {"!*/c", "a", true},
    {"!*/c", "a.b", true},
    {"!*/c", "a/a", true},
    {"!*/c", "a/b", true},
    {"!*/c", "b/a", true},
    {"!*/c", "b/b", true},
    {"!*a*", "foo", true},
    {"!a/*", "a", true},
    {"!a/*", "a.b", true},
    {"!a/*", "b/a", true},
    {"!a/*", "b/b", true},
    {"!a/*", "b/c", true},
    {"!f*b", "bar", true},
    {"!f*b", "foo", true},
    {"!.md", ".md", false},
    {"!**/*.md", "a.js", true},
    {"!**/*.md", "c.txt", true},
    {"!*.md", "a.js", true},
    {"!*.md", "b.md", false},
    {"!*.md", "c.txt", true},
    {"!*.md", "abc.md", false},
    {"!*.md", "abc.txt", true},
    {"!*.md", "foo.md", false},
    {"!.md", "foo.md", true},
    {"!*.md", "a.js", true},
    {"!*.md", "b.txt", true},
    {"!*.md", "c.md", false},
    {"!a/*/a.js", "a/a/a.js", false},
    {"!a/*/a.js", "a/b/a.js", false},
    {"!a/*/a.js", "a/c/a.js", false},
    {"!a/*/*/a.js", "a/a/a/a.js", false},
    {"!a/*/*/a.js", "b/a/b/a.js", true},
    {"!a/*/*/a.js", "c/a/c/a.js", true},
    {"!a/a*.txt", "a/a.txt", false},
    {"!a/a*.txt", "a/b.txt", true},
    {"!a/a*.txt", "a/c.txt", true},
    {"!a.a*.txt", "a.a.txt", false},
    {"!a.a*.txt", "a.b.txt", true},
    {"!a.a*.txt", "a.c.txt", true},
    {"!a/*.txt", "a/a.txt", false},
    {"!a/*.txt", "a/b.txt", false},
    {"!a/*.txt", "a/c.txt", false},
    {"!*.md", "a.js", true},
    {"!*.md", "b.txt", true},
    {"!*.md", "c.md", false},
    {"!**/a.js", "a/a/b.js", true},
    {"!a/**/a.js", "a/a/a/a.js", false},
    {"!a/**/a.js", "b/a/b/a.js", true},
    {"!a/**/a.js", "c/a/c/a.js", true},
    {"!**/*.md", "a/b.js", true},
    {"!**/*.md", "a.js", true},
    {"!**/*.md", "a/b.md", false},
    {"**/*.md", "a/b.js", false},
    {"**/*.md", "a.js", false},
    {"**/*.md", "a/b.md", true},
    {"**/*.md", "a.md", true},
    {"!**/*.md", "a/b.js", true},
    {"!**/*.md", "a.js", true},
    {"!**/*.md", "a/b.md", false},
    {"!*.md", "a/b.js", true},
    {"!*.md", "a.js", true},
    {"!*.md", "a/b.md", true},
    {"!*.md", "a.md", false},
    {"!**/*.md", "a.js", true},
    {"!**/*.md", "c.txt", true},
    // source: test/js/bun/glob/match.test.ts > test("question_mark")
    {"\?", "a", true},
    {"\?", "aa", false},
    {"\?", "ab", false},
    {"\?", "aaa", false},
    {"\?", "abcdefg", false},
    {"\?\?", "a", false},
    {"\?\?", "aa", true},
    {"\?\?", "ab", true},
    {"\?\?", "aaa", false},
    {"\?\?", "abcdefg", false},
    {"\?\?\?", "a", false},
    {"\?\?\?", "aa", false},
    {"\?\?\?", "ab", false},
    {"\?\?\?", "aaa", true},
    {"\?\?\?", "abcdefg", false},
    {"a\?c", "aaa", false},
    {"a\?c", "aac", true},
    {"a\?c", "abc", true},
    {"ab\?", "a", false},
    {"ab\?", "aa", false},
    {"ab\?", "ab", false},
    {"ab\?", "ac", false},
    {"ab\?", "abcd", false},
    {"ab\?", "abbb", false},
    {"a\?b", "acb", true},
    {"a/\?/c/\?/e.md", "a/bb/c/dd/e.md", false},
    {"a/\?\?/c/\?\?/e.md", "a/bb/c/dd/e.md", true},
    {"a/\?\?/c.md", "a/bbb/c.md", false},
    {"a/\?/c.md", "a/b/c.md", true},
    {"a/\?/c/\?/e.md", "a/b/c/d/e.md", true},
    {"a/\?/c/\?\?\?/e.md", "a/b/c/d/e.md", false},
    {"a/\?/c/\?\?\?/e.md", "a/b/c/zzz/e.md", true},
    {"a/\?/c.md", "a/bb/c.md", false},
    {"a/\?\?/c.md", "a/bb/c.md", true},
    {"a/\?\?\?/c.md", "a/bbb/c.md", true},
    {"a/\?\?\?\?/c.md", "a/bbbb/c.md", true},
    // source: test/js/bun/glob/match.test.ts > test("braces")
    {"{a,b,c}", "a", true},
    {"{a,b,c}", "b", true},
    {"{a,b,c}", "c", true},
    {"{a,b,c}", "aa", false},
    {"{a,b,c}", "bb", false},
    {"{a,b,c}", "cc", false},
    {"a/{a,b}", "a/a", true},
    {"a/{a,b}", "a/b", true},
    {"a/{a,b}", "a/c", false},
    {"a/{a,b}", "b/b", false},
    {"a/{a,b,c}", "b/b", false},
    {"a/{a,b,c}", "a/c", true},
    {"a{b,bc}.txt", "abc.txt", true},
    {"foo[{a,b}]baz", "foo{baz", true},
    {"a{,b}.txt", "abc.txt", false},
    {"a{a,b,}.txt", "abc.txt", false},
    {"a{b,}.txt", "abc.txt", false},
    {"a{,b}.txt", "a.txt", true},
    {"a{b,}.txt", "a.txt", true},
    {"a{a,b,}.txt", "aa.txt", true},
    {"a{a,b,}.txt", "aa.txt", true},
    {"a{,b}.txt", "ab.txt", true},
    {"a{b,}.txt", "ab.txt", true},
    {"a{a,b/}*.txt", "aa.txt", true},
    {"a{a,b/}*.txt", "ab/.txt", true},
    {"a{a,b/}*.txt", "ab/a.txt", true},
    {"{a/,}a/**", "a/a/", true},
    {"{a/,}a/**", "a/a/a", true},
    {"{a/,}a/**", "a/a/", true},
    {"{a/,}a/**", "a/a/a/", true},
    {"{a/,}b/**", "a/b/a/", true},
    {"{a/,}b/**", "b/a/", true},
    {"a{,/}*.txt", "a.txt", true},
    {"a{,/}*.txt", "ab.txt", true},
    {"a{,/}*.txt", "a/b.txt", true},
    {"a{,/}*.txt", "a/ab.txt", true},
    {"a{,.*{foo,db},\\(bar\\)}.txt", "a.txt", true},
    {"a{,.*{foo,db},\\(bar\\)}.txt", "adb.txt", false},
    {"a{,.*{foo,db},\\(bar\\)}.txt", "a.db.txt", true},
    {"a{,*.{foo,db},\\(bar\\)}.txt", "a.txt", true},
    {"a{,*.{foo,db},\\(bar\\)}.txt", "adb.txt", false},
    {"a{,*.{foo,db},\\(bar\\)}.txt", "a.db.txt", true},
    {"a{,.*{foo,db},\\(bar\\)}", "adb", false},
    {"a{,.*{foo,db},\\(bar\\)}", "a.db", true},
    {"a{,*.{foo,db},\\(bar\\)}", "adb", false},
    {"a{,*.{foo,db},\\(bar\\)}", "a.db", true},
    {"{,.*{foo,db},\\(bar\\)}", "a", false},
    {"{,.*{foo,db},\\(bar\\)}", "adb", false},
    {"{,.*{foo,db},\\(bar\\)}", "a.db", false},
    {"{,.*{foo,db},\\(bar\\)}", ".db", true},
    {"{,*.{foo,db},\\(bar\\)}", "a", false},
    {"{*,*.{foo,db},\\(bar\\)}", "a", true},
    {"{,*.{foo,db},\\(bar\\)}", "adb", false},
    {"{,*.{foo,db},\\(bar\\)}", "a.db", true},
    {"a/b/**/c{d,e}/**/xyz.md", "a/b/c/xyz.md", false},
    {"a/b/**/c{d,e}/**/xyz.md", "a/b/d/xyz.md", false},
    {"a/b/**/c{d,e}/**/xyz.md", "a/b/cd/xyz.md", true},
    {"a/b/**/{c,d,e}/**/xyz.md", "a/b/c/xyz.md", true},
    {"a/b/**/{c,d,e}/**/xyz.md", "a/b/d/xyz.md", true},
    {"a/b/**/{c,d,e}/**/xyz.md", "a/b/e/xyz.md", true},
    {"*{a,b}*", "xax", true},
    {"*{a,b}*", "xxax", true},
    {"*{a,b}*", "xbx", true},
    {"*{*a,b}", "xba", true},
    {"*{*a,b}", "xb", true},
    {"*\?\?", "a", false},
    {"*\?\?\?", "aa", false},
    {"*\?\?\?", "aaa", true},
    {"*****\?\?", "a", false},
    {"*****\?\?\?", "aa", false},
    {"*****\?\?\?", "aaa", true},
    {"a*\?c", "aaa", false},
    {"a*\?c", "aac", true},
    {"a*\?c", "abc", true},
    {"a**\?c", "abc", true},
    {"a**\?c", "abb", false},
    {"a**\?c", "acc", true},
    {"a*****\?c", "abc", true},
    {"*****\?", "a", true},
    {"*****\?", "aa", true},
    {"*****\?", "abc", true},
    {"*****\?", "zzz", true},
    {"*****\?", "bbb", true},
    {"*****\?", "aaaa", true},
    {"*****\?\?", "a", false},
    {"*****\?\?", "aa", true},
    {"*****\?\?", "abc", true},
    {"*****\?\?", "zzz", true},
    {"*****\?\?", "bbb", true},
    {"*****\?\?", "aaaa", true},
    {"\?*****\?\?", "a", false},
    {"\?*****\?\?", "aa", false},
    {"\?*****\?\?", "abc", true},
    {"\?*****\?\?", "zzz", true},
    {"\?*****\?\?", "bbb", true},
    {"\?*****\?\?", "aaaa", true},
    {"\?*****\?c", "abc", true},
    {"\?*****\?c", "abb", false},
    {"\?*****\?c", "zzz", false},
    {"\?***\?****c", "abc", true},
    {"\?***\?****c", "bbb", false},
    {"\?***\?****c", "zzz", false},
    {"\?***\?****\?", "abc", true},
    {"\?***\?****\?", "bbb", true},
    {"\?***\?****\?", "zzz", true},
    {"\?***\?****", "abc", true},
    {"*******c", "abc", true},
    {"*******\?", "abc", true},
    {"a*cd**\?**\?\?k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?k***", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?***k", "abcdecdhjk", true},
    {"a**\?**cd**\?**\?\?***k**", "abcdecdhjk", true},
    {"a****c**\?**\?\?*****", "abcdecdhjk", true},
    {"a/\?/c/\?/*/e.md", "a/b/c/d/e.md", false},
    {"a/\?/c/\?/*/e.md", "a/b/c/d/e/e.md", true},
    {"a/\?/c/\?/*/e.md", "a/b/c/d/efghijk/e.md", true},
    {"a/\?/**/e.md", "a/b/c/d/efghijk/e.md", true},
    {"a/\?/e.md", "a/bb/e.md", false},
    {"a/\?\?/e.md", "a/bb/e.md", true},
    {"a/\?/**/e.md", "a/bb/e.md", false},
    {"a/\?/**/e.md", "a/b/ccc/e.md", true},
    {"a/*/\?/**/e.md", "a/b/c/d/efghijk/e.md", true},
    {"a/*/\?/**/e.md", "a/b/c/d/efgh.ijk/e.md", true},
    {"a/*/\?/**/e.md", "a/b.bb/c/d/efgh.ijk/e.md", true},
    {"a/*/\?/**/e.md", "a/bbb/c/d/efgh.ijk/e.md", true},
    {"a/*/ab\?\?.md", "a/bbb/abcd.md", true},
    {"a/bbb/ab\?\?.md", "a/bbb/abcd.md", true},
    {"a/bbb/ab\?\?\?md", "a/bbb/abcd.md", true},
    // source: test/js/bun/glob/match.test.ts > test("trailing globstar patterns")
    {"C:/Users/window/AppData/Local/Temp/testworkspace_V7osKW**", "C:/Users/window/AppData/Local/Temp/testworkspace_V7osKW/packages/malfored1", false},
    {"foo**", "foobar", true},
    {"foo**", "foo", true},
    {"foo/**", "foo", false},
    {"foo/**", "foo/", true},
    {"foo/**", "foo/bar", true},
    {"foo/**", "foo/bar/baz", true},
    {"foo/**", "foo/bar/baz/", true},
    {"foo/**", "food/bar", false},
    {"foo/**/**", "foo", false},
    {"foo/**/**", "foo/", true},
    {"foo/**/**", "foo/bar", true},
    {"foo/**/**", "foo/bar/baz", true},
    {"foo/**/**/**", "foo/bar/baz", true},
    {"foo/**/*.js", "foo/bar.js", true},
    {"foo/**/*.js", "foo/bar/baz.js", true},
    {"foo/**/*.js", "foo/bar/baz/qux.js", true},
    {"foo/**/*.js", "foo/bar.txt", false},
    {"foo/**/*.js", "foo/bar/baz.txt", false},
    {"**/foo/**", "foo/", true},
    {"**/foo/**", "a/foo/", true},
    {"**/foo/**", "a/b/foo/", true},
    {"**/foo/**", "foo/bar", true},
    {"**/foo/**", "a/foo/bar", true},
    {"**/foo/**", "a/b/foo/bar/baz", true},
    {"/**", "/", true},
    {"/**", "/foo", true},
    {"/**", "/foo/bar", true},
    {"foo///**", "foo///bar", true},
    {"foo///**", "foo/bar", false},
    {"./**", ".", false},
    {"./**", "./", true},
    {"./**", "./foo", true},
    {"./**", "./foo/bar", true},
    {"./**", "../foo", false},
    {"\xF0\x9F\x8E\x89/**", "\xF0\x9F\x8E\x89/", true},
    {"\xF0\x9F\x8E\x89/**", "\xF0\x9F\x8E\x89/\xF0\x9F\x8C\x9F", true},
    {"\xF0\x9F\x8E\x89/**", "\xF0\x9F\x8E\x89/\xF0\x9F\x8C\x9F/\xE2\x9C\xA8", true},
    {"foo/{bar,baz}/**", "foo/bar/", true},
    {"foo/{bar,baz}/**", "foo/baz/qux", true},
    {"foo/{bar,baz}/**", "foo/qux/", false},
    {"foo/[a-z]/**", "foo/a/", true},
    {"foo/[a-z]/**", "foo/z/bar", true},
    {"foo/[a-z]/**", "foo/1/", false},
    {"foo\\*/**", "foo*/", true},
    {"foo\\*/**", "foo*/bar", true},
    {"foo\\*/**", "foobar/", false},
    {"FoO/**", "FoO/BaR", true},
    {"FoO/**", "foo/bar", false},
    {"foo/**", "foobar/", false},
    {"foo/**", "foobar/baz", false},
    {"foo**", "foo/bar", false},
    {"foo**", "foobar", true},
    {"foo/**", "foo\\bar", false},
    {"foo/**", "foo/../bar", true},
    {"foo/**", "foo/bar/../../baz", true},
    {"foo/**", "foo/bar/../..", true},
    {"foo/**//", "foo///bar", false},
    {"foo/**", "foo//bar", true},
    {"a/**/", "a/b//", true},
    {"foo/**/", "foo/bar//", true},
    {"foo/**", "foo/A\xCC\x8A", true},
    {"foo/**", "foo/\xC3\x85", true},
};
// clang-format on

void test_static_vectors() {
    for (const auto& v : kMatchVectors) {
        check_match(v.pattern, v.path, v.expected, "match.test.ts static");
    }
}

// source: match.test.ts > test("deeply nested braces do not overflow depth counters")
void test_deeply_nested_braces() {
    const std::string opens(300, '{');
    const std::string closes(300, '}');
    constexpr std::string_view src{"deeply nested braces"};

    // First branch matches; branch skipping must scan past >255 nested braces
    // to find the closing brace of the outer group.
    std::string pattern{"{a," + opens + closes + "}"};
    check_match(pattern, "a", true, src);
    check_match(pattern, "b", false, src);

    // Deeply nested braces in the first (non-matching) branch, second branch matches.
    pattern = "{" + opens + closes + ",a}";
    check_match(pattern, "a", true, src);

    // Deep nest with content, surrounded by matching branches on both sides.
    pattern = "{a," + opens + "x" + closes + ",b}";
    check_match(pattern, "a", true, src);
    check_match(pattern, "b", true, src);
    check_match(pattern, "y", false, src);

    // Same shape inside a wildcard backtrack.
    pattern = "*{a," + opens + closes + "}";
    check_match(pattern, "za", true, src);

    // >32767 consecutive `{`: the group never closes, so nothing matches.
    const std::string unclosed(40000, '{');
    check_match(unclosed, "a", false, src);
    check_match(unclosed, "{", false, src);
}

// source: match.test.ts > test("trailing globstar patterns") > "Very long paths"
void test_very_long_path() {
    std::string longPath;
    for (int i{0}; i < 100; ++i) {
        longPath += "a/";
    }
    check_match("a/**", longPath, true, "trailing globstar patterns");
}

#include "glob_match_fixtures.inc"

// JS String.prototype.split("\n"): empty pieces are kept, including a
// trailing one when the text ends with '\n'.
std::vector<std::string_view> split_lines(std::string_view text) {
    std::vector<std::string_view> parts;
    std::size_t start{0};
    while (true) {
        const auto pos{text.find('\n', start)};
        if (pos == std::string_view::npos) {
            parts.push_back(text.substr(start));
            break;
        }
        parts.push_back(text.substr(start, pos - start));
        start = pos + 1;
    }
    return parts;
}

// source: match.test.ts > test("braces") fixture table:
// `matched` (every filelist entry the pattern matches, in file order) must
// equal the corresponding matched-N.txt contents (toEqual semantics).
void test_brace_fixtures() {
    const auto allFilePaths{split_lines(kGlobFixtureFileList)};
    int index{0};
    for (const auto& fixture : kGlobFixtureCases) {
        const auto shouldMatch{split_lines(fixture.expected)};
        std::vector<std::string_view> matched;
        for (const auto& filepath : allFilePaths) {
            if (match(fixture.pattern, filepath)) {
                matched.push_back(filepath);
            }
        }
        ++gChecks;
        if (matched != shouldMatch) {
            report_failure(std::format(
                "[braces fixtures[{}]] pattern \"{}\": {} matches, expected {}", index,
                fixture.pattern, matched.size(), shouldMatch.size()));
            // Print the first divergence to aid debugging.
            const auto n{std::min(matched.size(), shouldMatch.size())};
            for (std::size_t i{0}; i < n; ++i) {
                if (matched[i] != shouldMatch[i]) {
                    std::println("    first divergence at [{}]: got \"{}\", expected \"{}\"", i,
                                 matched[i], shouldMatch[i]);
                    break;
                }
            }
        }
        ++index;
    }
}

// ── scan (real filesystem traversal) ────────────────────────────────────────
//
// Builds a temporary directory tree in-process, runs mbun::glob::scan over it,
// and verifies the matched relative paths. Covers the DEFERRED scan surface:
// **/*/?/[...]/{a,b}, dotfiles (default + dot:true + leading-dot pattern),
// onlyFiles, absolute, and directory pruning. Not a port of bun's scan.test.ts
// (which diffs against fast-glob over the bun repo); the semantics asserted
// here match bun's GlobWalker eval logic.

void write_file(const std::filesystem::path& p, std::string_view contents) {
    std::filesystem::create_directories(p.parent_path());
    std::ofstream f{p};
    f << contents;
}

std::filesystem::path make_scan_tree() {
    std::error_code ec;
    const auto uniq{std::chrono::steady_clock::now().time_since_epoch().count()};
    const std::filesystem::path base{std::filesystem::temp_directory_path(ec)
                                     / std::format("mbun-glob-scan-{}", uniq)};
    std::filesystem::remove_all(base, ec);
    std::filesystem::create_directories(base);
    write_file(base / "a.ts", "");
    write_file(base / "a.js", "");
    write_file(base / "b.txt", "");
    write_file(base / ".hidden.ts", "");
    write_file(base / "src" / "foo.ts", "");
    write_file(base / "src" / "bar.js", "");
    write_file(base / "src" / "nested" / "deep.ts", "");
    write_file(base / "src" / "nested" / ".secret.ts", "");
    write_file(base / "node_modules" / "pkg" / "index.js", "");
    write_file(base / ".git" / "config", "");
    std::filesystem::create_directories(base / "emptydir");
    return base;
}

std::vector<std::string> sorted(std::vector<std::string> v) {
    std::ranges::sort(v);
    return v;
}

void check_scan(std::string_view label, std::vector<std::string> got,
                std::vector<std::string> expected) {
    ++gChecks;
    const std::vector<std::string> g{sorted(std::move(got))};
    const std::vector<std::string> e{sorted(std::move(expected))};
    if (g != e) {
        std::string gotStr;
        for (const auto& s : g) {
            gotStr += s + " ";
        }
        std::string expStr;
        for (const auto& s : e) {
            expStr += s + " ";
        }
        report_failure(std::format("scan[{}]: got [{}] expected [{}]", label, gotStr, expStr));
    }
}

void test_scan() {
    using mbun::glob::scan;
    using mbun::glob::ScanOptions;

    const std::filesystem::path base{make_scan_tree()};
    const std::string cwd{base.string()};
    auto opt = [&](ScanOptions o) {
        o.cwd = cwd;
        return o;
    };

    check_scan("*.ts", scan("*.ts", opt({})), {"a.ts"});
    check_scan("**/*.ts", scan("**/*.ts", opt({})),
               {"a.ts", "src/foo.ts", "src/nested/deep.ts"});
    check_scan("src/*.ts", scan("src/*.ts", opt({})), {"src/foo.ts"});
    check_scan("src/**/*.ts", scan("src/**/*.ts", opt({})),
               {"src/foo.ts", "src/nested/deep.ts"});
    check_scan("**/*.js", scan("**/*.js", opt({})),
               {"a.js", "src/bar.js", "node_modules/pkg/index.js"});
    check_scan("**/node_modules/**/*.js", scan("**/node_modules/**/*.js", opt({})),
               {"node_modules/pkg/index.js"});
    check_scan("*.{ts,js}", scan("*.{ts,js}", opt({})), {"a.ts", "a.js"});
    check_scan("a.?s", scan("a.?s", opt({})), {"a.ts", "a.js"});
    check_scan("[ab].txt", scan("[ab].txt", opt({})), {"b.txt"});

    // dotfiles: excluded by default, included with dot:true, and matched by a
    // pattern component that itself starts with a literal '.'.
    ScanOptions dotOpt{};
    dotOpt.dot = true;
    check_scan("*.ts dot:true", scan("*.ts", opt(dotOpt)), {"a.ts", ".hidden.ts"});
    check_scan(".*", scan(".*", opt({})), {".hidden.ts"});
    check_scan("**/*.ts dot:true", scan("**/*.ts", opt(dotOpt)),
               {"a.ts", ".hidden.ts", "src/foo.ts", "src/nested/deep.ts",
                "src/nested/.secret.ts"});

    // onlyFiles:false includes matching directories.
    ScanOptions dirsOpt{};
    dirsOpt.onlyFiles = false;
    check_scan("src onlyFiles:false", scan("src", opt(dirsOpt)), {"src"});
    check_scan("* onlyFiles:false", scan("*", opt(dirsOpt)),
               {"a.ts", "a.js", "b.txt", "src", "node_modules", "emptydir"});

    // absolute paths.
    const std::string absTs{(base / "a.ts").generic_string()};
    check_scan("*.ts absolute", scan("*.ts", opt([&] {
                   ScanOptions o{};
                   o.absolute = true;
                   return o;
               }())),
               {absTs});

    std::error_code ec;
    std::filesystem::remove_all(base, ec);
}

}  // namespace

int main() {
    test_static_vectors();
    test_deeply_nested_braces();
    test_very_long_path();
    test_brace_fixtures();
    test_scan();

    if (gFailures > MAX_FAILURE_PRINTS) {
        std::println("  ... {} more failures not shown", gFailures - MAX_FAILURE_PRINTS);
    }
    std::println("test_glob: {} checks, {} failures", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
